local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr(data) m=string.sub(data, 0, 255) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


render.add_font(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('JqATOGhhlPHEwwAJSmBvcWwesqJrMgnliTFvsRZKkqmiSuNVhNdUqfqSIHOAWKTDVnmLaZsyeKsAzVaxUetSQFMxvTkUoooUqSGumGtYNVikzcBPKHBVzQiBiZtJKjkBEWTrjbLKiFIkpVyXfZcRMAJjPRUnhygdXoFngFxYkyncEEAQBdNLiOxYyVvsqPYmNyKeNaooveorBKTEEBXhuolrJrqdNbKPcXGUYAGqFimbPFkIapDmgHDrEhZaVYFbmlra2E='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wfCMvqvbmenxjLUgtQceiOnDYljccVxBgmEYdiixQUPjybKEJLHDTimhpdtldPrbqDscZtUkeZXZjGmqOYcJIvwsJBxjqxyRkPOlzQeexrTsCypWqapYqWBbByXTvxmzVBoOsXYHcLJufQTJzpJAlgNubvLYzqzghHIlhzaxlqEBpZpaNziyaBckUjbhNLLytRGpFLbnTzWhaZWNexzoymerzkAOvuUGeOBSrxepwsZRqHXyxuEAqlIuBsnuBAiVmVyZGFuYQ=='), 30, 500, 2)

cheat.print(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wmacfANTOwaejHWEpLochmWYfxAEnRocdsgDJryFuciTkTeulSoCLhyMauCkBDYdjLmwsyHIHzfozMpKgUdhCZmuVYKvGjqvymaJKKjooHXbWAYdgtokXOGXWZBGblgStoQAtJkkbTGcLSirqMgqfEXOYNIIuKvwsiTzAEAEdGXkZWZbMLcdsuXbeQtvwUJWYcGRueTrrfPWAyKhjWQeAYlrTRhTRdgJgJAnuGTUkDcUREDIrLtfdXBRmPFbLIRSHlwZXJZYXcgW1YxLjNdIFdlbGNvbWUg') .. cheat.get_username() .. KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('rIPRxluFuBDdZANqFDXdtebLONevrWZaHxmSdPwBtybnVPwvKYtYAWgvvrzJbeqaxQFtLINtPVktywAVgFGgRGBoCthIVvqmpggALRlIKhcKsEEgariDjPaMRARyIlypGSdfJdEMXYZufBKJdGpKahVvwYhJPSvRJoeKqiczQdnLWQuCyYKdItuzldDewmEhoxgXYQkGJQKMztQNWKbNStfJXqJfossYJtaqZEnxzsDxXFjhdIsaUIbxNTCkOVXIFVJRCA=') .. cheat.get_uid(), c_color.new(255,255,255,255))

menu.add_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('VBOUbHIcFryONbbhutdVJrutAolAcftfYtTuRPQfNqvJLQiVtLLrrrwkvUdlrrKGhmautkToMKsrNjiqWrqOLHhWREvzUpzNmoBmhekCSMwDWFiZOXPfxhFkTGQIRMRceOCfEzPccaqTOlSQruAvSUkySYHSqLdtLxusnreKnRkHfaUtlNkWGZbVPioAZBclgrGCZNKTIQJqbByKFAGVngbUyuOplUkLAfsQrPNreYimXrtnmmRrjzETeWnVEeMQW50aUFudGlBaW0='), false)
menu.checkbox(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('qWKagRgXQIBfFxQabTmMfgBNoYHHeUsUGiBzhNfymiIEhgALboxbyGSzqKzpraADuiCOiZaUZkBOoKluJWjhAOpuyOitAkUVvGxxiXKYvKGJfFtLnEsTcxJiOcmccIFHQjyupesSRxHctXVoyMRcejKsnliclxstDPdSIQzTYfGCMhkQEXsoKLrVHBiNoUfcmPVoQoKDNPJfGaZrMarjiIJSzwjcFqiXKcCQdyJmMQShrPqzuqfskNIVHOJfdPmLS0tLS1IeXBlcllhdyBbVjEuM10tLS0tLS0='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ncclrjRwliAcUsqOaBKGdYijcVahKRDLinIUagNXwNVQeoMiNyZGLpMpFTRgsdtlEKzPTEcFvdCwLFawRGepqccEfmWVMLsaKGjFOHUNWXmtijZTYukiDiWVCbgqfERjlJZyxYXJgyECcmjRDRNZmyrYwuCoWMSGETfUjzvAadMVJaOVkgvGpwrymgeqaxeNCEqrrUGlxpsnafAjoKNgoEftsaramzkVMTyFZpEROKRAyvSpdDVvdPbqZFEmCWbQW50aUFudGlBaW0='))

menu.set_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('sFsvdGXztJBwazpQWfmcJUPqquLkbNHcAGGXXdOxHyLXwstKCbsFgjtIqyyHUcXYrMQAMcOLzxnyeiDWiXcGYEutvaHzLbeCRoxyDJVFZgFyWfCefqDdFrMpoOQVqmUBvWqulshvYAFVIOvjOumHIrfkIVRVtZhJGhsMSdpqKNKxhURsrWKFNtaNZNbXJujklyZaTXfnELRkUJFvDsiZHVdJaKSmtrQqTlwGfxvMwlYUivYtEhVzOqIFfYUWFKIQW50aUFudGlBaW0='), true)

menu.add_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('UTQoPGLwNifzkDudzDDxuNOvcDyPWBgmwmtkbashSrIfvgFtxDeAYixdvwEhPyQeqrPnpZgMWqfPNVYPChWzlEaCLQPNqLZqPHOqBWgcghiGFyoIuFHaQHbwxpMIPHEfJVBpPSIrMmfrjTKBQewFLvcmACJxOuFXsLwexojRtWDlLxLXTwrQAykBYtAQcscjBajhIakPWZmpVIFQvHRFOWtILORHTBQgLlFjSEOJOCqLpvmCTyleOgkomJbURpmQW5pbUJyZWFr'), false)
menu.checkbox(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fWPlvSFhjwYySEdeDijffdhRibivkZVjfLtXfylwHwIQhpyJGzsNVnBcBFkoWFrojTvMzjUekiPZCkxqkanNODgHPYaOxRsWSWXAXKkMYTTYBgVlpTTMucvkgFeyRzOLkXulGzPhrQULcZCDRAedzBTCrSxQeklWNRqMZFrTezTbsqHDcYKJEEdVMjfKZVdCiOOIYmyuswLtxqiNyozkuCIOBbSFijcYyUYBOxSzuZhfFajinNbhFxmWLpzZvNWQW5pbSBCcmVha2Vy'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mxmecHqOhkpWcIsfLQLcvpOopVJJKCJkTWSPMTGRBnSGyopZVWwrILTGQIzEsZElwsspahImHurXwWaQiOcXFpPHjEUDzWGTWJfTmfordGxBwYkgofGEKLXJhTirOlCFfEuhgipmHqsBPFyrHFsKDzOjmRBuBcgQzzvGvkRvlclLMBCmGHHqLNlHiAguKlLLyfLpoxcUgYgeNXwQTJWFPlnAHIZUzGuLQNBNDkFqoDhnUdJQzKyFUaEYMjOJLHNQW5pbUJyZWFr'))

menu.add_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('qXqNRurJTghJlCiYiIjwpGMHLYMOwuPMxellbGgpgSDVVnykorIPJJTUKwaKaKGFcXtWjZwBzfbrmOqYYXcgCdNkPxjHQyYrujUIJvFZDbBspWKiEAfKvGCzpsyCCseBOMOkelmtcyJphiZAQVNvVButisnzvKrDdWWfhEbBBbWaNkwAWJiILuvyVDaDFdgFOFaYnJmjzecUkGGGdduYstqQJdqRfdHBFDLWZzspjwRxRFWrHFctgmMzBaUNHCWZGVmZW5zaXZlX2luX2Fpcg=='), false)
menu.checkbox(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ilxqbKPyHQFxRpQudPNruShZsIvpQVDsJrteYRUebMFruyuSjguUAslriWcwZKbjcQBzJCUjSmQVKGIAYgvqcDAzpExcvXwYxkmWTVIkmKftZhUwOCMzNGjsJGmYWTdYAYytHDbKxhyvdEgdzxffeNxDDlkdspNFqQehqXqdIwYVZEKfhQOyeNwtDvgYpNlbqtXjozecuBVUcrnUHJIryWcQJrlOQOWIrAAtsqVeJYtwmSoMcYhMrzTVMhFWAphRGVmZW5zaXZlIGluIGFpcg=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jYNdAHpILBwgaiPudRSEQMvxxEzLZabELNfRVKDJBfVGIkKUypxWHwjBUWUCWOEHbJEiVpqwjwjdKcRWvSoKZRYBxkzfHXGcdzwYycbMjPTjlORmbnPPJmtaosfnbVBDqhKWvtxkAEOBVBJNFwdQNIlHIwBCtDnaBPCSdOFsYUsiDtuJXsFpRHZEubqZoVFKsByforzqXVevGpFbxcCjOKRryJOFobgCdVlmXYjPpIRcUPqvyTLjLgMCUHPrpUJZGVmZW5zaXZlX2luX2Fpcg=='))

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('dVckigtYvlkowdHokGCmtvMgvFoHXyGRJnMVGPDWvXwDdaukunBjkzFURgdQWcLtYXkywEGIoEDIJhHaNgoibhFrusDEPnulyPIxQKldNMAInGbefZMnuHqJNKXpHUUESFtQYYbSGbQVTjyFPWhmQTWnwDciZMsYKksdGgGDCKaorssOyguNcNoyQRNaCNnNHaxjRjlxMiLxHBVrwazHVHrmeAJlqMAJAAVVOexZsmwyAtppLzmYOHFKKMnjohdYW50aWFpbV9tb2Rl'), 0)
menu.combo(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('NpVaUxuJAXwDaGoabvOVOqlFESMwRcyqxtWRpHYlRqFkqnTGqEaZqoLwpLGvchryPmSQVBfxHnixMfKrBSJXaUINpLrzQjgTElhkhWQKGkbAbxfBvZAStwsIioNUVFMMPpnipSpmwuSChKFohGEfiHWQUwVfrqEihHMCpMWOYAFIDqHFoYjeYOStAdXCFavwueVaSEuvKxWEOfqAuRNlbyWCKIoQesVFGAjMDAWIhVHZXQjHFYsellOvspXPXmEQW50aWFpbSBNb2Rl'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fuWYJKQFGvxIHrBirJiQmKRJkikNfpZtziZbbWLsWOvhMkDXTuvabqVXjQNerQbOOPHeQpNPfSNhFQjWqBDWiDVBWhRgMbmxpYwWvnFoCrfKiPsfCQBDNQaxEccyPAvhYjYlhJsdODtGrweNAIAdZgTmXCEClfYIDmrxAwNNLGZLxSFLqzdlYLQbJYxXqFbaZMeOxgXuNGmHOzWkHtFBGRnLGkmXwYkDRqGtGklRhgWbizGgQZAbfnKonIILFDQYW50aWFpbV9tb2Rl'), {KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('OcbpaxtjdatRMlnfSAlTpryQGPbFhITIrImiIvomJHjKQZkgOpUyvXZVaSUvAKIKzPvVAaFbYCjrRUGbZjoSqlpDWmfRrkKMvUCLDDStvKZHOFktSScyzqNwXxbcBkMZFOZvMNuWeYjsIuxzWxlwxUTNJijGhGqnaBUuExYnyqFpyyZEKHkqKmVobmQTINiEhvwNGpgzjagGujLvwgzntzaySGLTkfIzcixsvzGYIAsXSRrjmVGmCLzVOREbPZwSHlwZXJZYXcgUHJlc2V0'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fhqjmLkOPXygzqhGekkBQUVbwtnDApHWkvMsUBZljUOuWkewvaVpLFhPgALkLWjSwTgyNYqmboxsFxwbwCVWVuIiQkNyMBrwuMbNDbTsYWfYTLQiUHpFMQNCfxORlsrfdqyZKxjFDjNgSFusdEAvHSmAzyiliFmdAzBHNnzcDBkbSDfkEwLTztzAdiTVrulqydsoTgWzpsGqjkpETUPOrqtzamLfRokaBnQoEfqdulKjKegfoBRPbnRDCWBSpwZQ3VzdG9tIEFB')})

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('osBpntTXuomfxFlNpXbXcSaxYuBItPXkdrRlrlEBCXdndhDUyGaJIvHGZvAaNYVqoaMuSWhyxkFCAheYYGKQNvcoDQDhELVhfWuKBzEaevZidUGHiTLzMNlSCCpayJMlMNkEOUlpcXIFmNAgJFRCIieaOOBWAPQhtbdHkmEQQWQKlMqSrmQvWALBQzHmMGxdWwOmefAmujLIjQtVJnytKYdKHuMqvDMkfoDbninYmNYLJXBcAYhjflqnomFnxpQcGl0Y2hfbW9kZQ=='), 0)
menu.combo(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GFjGKFnzSjySGTKZRcyRIWruQJeFzCelahBQYgLuWLAmSXvEERkWBTaEFshTPmIbDqXILjdlgNPMFQWxXuQiQsColrbykEluDVgosjlKicgOihLYvMrFVyxiHMMdGLWIqYHyQucuHdMZdFwroQYAwLyDePYowmRNieUsELxvMIyLUZtlcHCzcECJuSXLnOqEnYZujZCuonyvDXHXzEqLZsqzscqXskCPPHPzhwzEInOwaPPdsJpEBqqygyDNvxCUGl0Y2ggTW9kZQ=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('XNmrCguzrMHASknXYyxQJjgbwmFMIebhJDdYFJJbvUGwpmoehWejIqyOLMAQZeoTeSgUMOHcxiqqfyMiTsiZMRxeFcQvOWHylcpPYQSYVuRNdHpYAncMzVlRWoXDRFhairnljlmzMYlLRrfGsKsQqciMgPHOwDkrMtEmJOycoLIdRXwNabRuOwPeOAHxnGjPSGKdHZaeOOPGZPwMOgraMUUVeuqgPoeobYNFvXqngTYIFXxVejVlRIaMtwEPwrZcGl0Y2hfbW9kZQ=='), {KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('dVCPcZMEgZVcjJTnNCUknmUFSAvfGroMUcsiKeMijsjynpQmBSnbzaaQeJBZOgTtSspRIJByLdJtlkMKorLhvqQyoIGiAvYLKDRznAhmVbyQKGpGTDgqjyOUdbYoEmwLduDlXQqcgtkoCIDytBVyCyBaQdqrItIowsNnNJQszIlthsbxagKJkcAPvpYXXUHjaqSoAwHUwZMdVBEDiPRJJAwibEbUrKtTdzcxmCXHXEzSNcnUQpxoeryyRbUaVvMRG93bg=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('HaSJWagzftWyalpZxueoSMLxBDPwDMkspPxNepISFuarJdHYRRSOlDrLuIDZGLGgMnPssZvmAixNqzXNSdwwloiHZIIUiAVJgVclREyxGUOfKShMiytyHRXZjVdzPQyhdMnENjWZTdoplVcXcKDsmtGsndPlCskfKkBrurKIcyDucqzgiMbaYPwVXzkIZLmOFSMpNzbXjKiANJRQdSpJVPtXXdtiHkgBPxSoefPyVNGOFBUpGUAxbvjdYhNsGMIVXA='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('LEUdKkfAaselZBYjAUQqhZXpPQdhLPzzWokenyFfBCIWxheAestZZZWrhlNvfguCIMhQsaepWhMrCTzIuoTQUsqwqveinIrzctjoqzgZIaDPKpCzLKiohSVYjwwufNiawdRIIocaoOnlFrIsGsOtOXVPSGzgnJAmSeneObvMIFNdAcQCNLVOITtjhvXccvxSrvJZZAIUGKWZarpXAqnmxTiurFYVfQuZLdptFgbzfsrGgmXpSSZWtHgLQBzwGxAUGl0Y2ggQnJlYWtlcg==')})

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ENxPJSQpFmHUPsKpgBSsOOImfoXetOhaLOuCiEHthoskfHtAsrgNmrFmAezThDrEdbUEeGtKQhcMDmPmwQXBhYWgpxlkyrbxacxJZBuHnoQNaWwKEXgvkhzaASgWpAHZivtqFPRvdDOQCMFkbIndiqHPPvBBIbhnRNuFGYUnBNzSLAxLhxxQDFDHxGxWNyqpzYgSTpnDudpQECGROlvvYvEJGXxMwQwjbJCOHJWxNGBzudKnRNDCVJPZBVIiXjxcGl0Y2hfYnJlYWtlcl92YWx1ZQ=='), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('OcUQcZCRTNZdnsGYtkXbMopVEioGBwswKhmptApxiYXhrRFbPCkTypQiMHTzzSpnlOjKITEOIZqoolZkwFdogTvAOUjywpqTgNDVNevuZTMirTOBNACXzMIkGrkfYivvLMNJzWFIdqqwHwdzPTWMvymHicYtzvfDhNJewzQKsgqFqOHsmGlbdHpiEgeslqQegcKxFVOcZaPPOlzQVQJcQdNSKvpJeHwugyvFlWerrTlpiIeesoLqhqndaQbmuVkUGl0Y2ggQnJlYWtlciBWYWx1ZQ=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('rJFibIvfSkUeOwkKDkNVNzznXKoOMUwQhCREKjZtiapVwysDOUnaoLZbsVvjuETBUYiuVoyshaZoODiAyNcVbkHJJIBgFjshscUgSUutfUCYOMEsAviMmoGlwPtUukEoQNMwtklqAFgKQHXdAMUJvUfBekjcLFnTKquICmjkAxWkYgzkRkJVTApUnVCbjuwqkRzQwbhSnvIgxJvdgcqBaBefvEYyyxMUhSNNidvEJaoFTPQFJXVBszigtsfuMBucGl0Y2hfYnJlYWtlcl92YWx1ZQ=='), 0, 89)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('IwHCPMtWGdJioZimJZywzlDsTBjzWEjDJKxLgWNvmbjabMYOevmXjLJhTxlxEeeHrLbnSymKvFPKtiQJOzEMPCbAsKbMvUajdTrxemtnjQeQHgBhvwrtuZTndPjgxfNBTtaAdQrNlDKbyvSJyBbRiIlXbOrlDOMNPAcMvzHFZFEPqIoDFtQdgCyUiaAMCBpaqDUqLMQshhawCSjZtavoWJDAWMicILOUiGCyrYCVIQVNbVxzdoEHLepmMYOYowteWF3X21vZGU='), 0)
menu.combo(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('slLqOLIYWfEzLnaSwXmuCqFYFBdwCpkOShdPgZmRaxxEjEpdsVqWnmTpmUogMGJCfKryedIiphXNlWTIiQCMOyAOgemTIfxAgACGsKMVzcZjIuemYClGuHxzVpIFfITIaBwwAjVysxJJMrrRQtdnGZSlmdTLigeEGOPFFiPRxHTUCyIqhDYUQzHqTrhzxoudSbgRCGYiFwzGONYFXHTkhKboRvWqGImQubTmMghKUsyUHrYfBjOtiYqSYWLbXXmWWF3IE1vZGU='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('rzxtPybpgOMjPLhShAGSaWBodAYexwJkgwSIPyhSeFRNDnFgOLXBdJIIbHtsqqgxHXiqglipJMmYuTQmJJdatIIbKmqIfoOGhMsxKuakMeixrrcCsrfWKuOjAnWmUcdmSARFsgNymEWzsbDWclaKqwOoekeCSoteMdpYrjgxQBPSkgtUVOoXasjkQFtyZltvQlRCpqpIZULnlDYWlrTNlQMpfkqZsXEMBHevGknXZYfxBQQmsbpxwJTNQKnakGSeWF3X21vZGU='), {KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('YLEoQIRJtntnrAvvabZxtgWkGTTDQhiEBpRizWJUBFiHDxpTGPjYXylxvboLPmtaoOnCHWwQwUqhzXFJoFgRcTBfeLpEAvTbmcTuKOALAkfldMerWDMnBqeAhQQgtfeYyMLASZFeYPIvGghbFXKHkNnIWBxxFpwawdkawbeCtncniqagEdzZKdGgOZpzUwnKCVwNpBqCjJtlDCRtQRLxeLWWSZffLPShfVolgodVvfHlsHbmMtnNPghwfqjqvwxQmFja3dhcmRz'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GdUzKwKQobxdVjBESRQwcxTndQBTLzFIHtCvKPTSPQkiOuyADgtzDMQQXwwroDmBIstSAuyUugwgykjDyYZmXjpnKGMVXhffiprVfpvHzcSBMjXseHDscOHEkAolvQxgIUUqQRHFFmivwwvXfOUAmGXDUTVPcScxbZiBEuaoohQlRspXBHqMrOckOPNqOsLEGEPtGfIYJbYZmNNtrhnGWmXujzxCLiXdXBsksybImrNuhCylUXOSnoQkwLzKjuPU3Bpbg=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BBmLBAhjhqTfybSipCDsKFgrYUFqWqhkcwXwWfJcSMkMhkeFdwAbmtsKnPcDswsfitmiJoUOOeZIzavSUeuguHmwxGkgQhISUFLatqnjHKiipLVGFLTKMvXUzczpmEUjMrtUWTFlRgBTITpflALBACfyPHuNsOYDUvYFwDzTjEnyvUoWaXtADHdsOHrDDHVLUkBjWlGEFSiEDJVkelnxQgJTIvDPQmcTUnraYyIxFaAwhyBqncmewEeuqbiJgEiU3dpdGNo'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GJFrkcdeLEoZyUmCrztKjItVzEQQdHYsTccSiYQzkNOgWzdHaShybPjnrknvoXSuwmYVuTMDniwyHmMhVwBLBWygFtiMqFypxJAILzqzxQqxtQOQDscvmZxApTwXDopEYYVXpIiXjWVEYftOZcgjntrFiWXFIlaQAPzEEqCoCcgpmfYsFjKZcNjGepmHQkMjyPlcSxQsSmsGkpuDPuLdxceENiuBgidFmsmspJuYilZjRoryTtPmgKHhNmREPODSml0dGVy'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('YYuYLdzEwolPetCcyRoJmVjITAKrDTDOqfmTSItzyilbLUlJcZyiKOnTrtVdrdsKIvZypvNymLrxhIVtbwesKtHkMBkDSlzgjdWUVWKazbcQSjNrkmpEpcnpFUohgatFCTgyMAgJZWsQCStIkCrkGzyiyOoUlklHNgCOkYnllRGBzKtJPnUolDCgxeTTJQssMGWyLEwFxtknaiBYpeycpCDZCiZUezbbyrihIZhoilYorOfUTHCJaLHJIaFiYefU3dpdGNoICsgSml0dGVyIChFeHBlcmltZW50YWwp')})

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('gHdgxbeGUmhLsMfCBotZrfugvvIXdbgWdksWqdseICaitHmxDuncZLuQCwFxCKuVjpLkLCdcGYjkjgujbObeBNYFAxMBYtHcrLDrGVimdYtTPnMZfMcCNrdltdoFekdwisyMIWoTIIvdSPRaANGoxjvTSqZgPmTPXPrmtzjtuCNFyeuIspkyYnoOZOuJOuLXfFHaKzygQqQgOwllMdsOHrkqCGZOBehbDtOBBlGSDLCPQeiHUkysQSebuvFXCsfc3Bpbl9zcGVlZA=='), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('HBWrLmePfoYtbCPDqUEqBFOFYJnExKhqyiBmPnUpytcIWZUYAhoKcdLbZZgSaIGRlOqaoVtLhVATqDcuGTFBKZAkMVKVCnzZWBEVcKLzZxHlzRwhEKvZViDOWGqpRJEJJYinXjAXOhhbMdFSnjzIxthLjzYgDKTpbrfxcJxenrOLOQAKidIEChojlYpgyMTZOtqizQcUEQtHAkRmozRkobkNNAHJthNrVHAiAaXkOwIjhzbCwjXFLZOiRkiPBTsU3BpbiBTcGVlZA=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('AjTtCwQPLNgbTWYgbgZHvowfBzaeeuReAbIQeMuaqXPHHKOwdcKSWnQcHXqNTnnUqVOlzgMCdEOoJaoYuOlboRoNtbVrJiMwGdWfhyfrdEFvNtdnfmBumFWqdmdDpDNkhZylVvguGMaaqdDGoHCejQlfKWGvcPaoNFtVtszjZUvYaXvPkPfOPAmaBkuXaqGTWyLOCkykZwtNgIlTvAOCnIJeoMQFCEwDHDmYMZmBwLNheVftHmeUktpjAKuCojvc3Bpbl9zcGVlZA=='), 1, 20)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('evTusFjTMTmlVsjjGSuXrqeYHxCsDRkbGBWoQPblQuusNUgYTJAAAAIJCNnRWafUpVnVbgzAjEkfFUnqANwrcrRdojshkXuPSwEnYhmCEjJyxflNVLRepVRVJvoNBxUiYFFLIfaiIXOEUsbOoEpHXrKoVAoHfvXrBSQOBmKHAZRjvAxfMwqenaYxanhMKWbSwnQFWFZtNvNRLbnUMjBWrOpkRsBtRziOpsVCifpYvgqkuDCNwrTXMceRXgllkxBc3dpdGNoX3NwZWVk'), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('OOwoSrQOvyfVKoxGCofZCMrgsSetXAwtAfHXoLaDXMwubwHREfsliENlXHfvMETNMLkLIKOWHowhxndqLhGSndASCBcjUfDGwjlgPbYhBHefNHPBUdIBeEeujZzidxDkFSSmDStBfsRquDAFtxGNdrVzJJureRxrccYFltvAoVMeCgZMcaNGUFZMudpovmLyvyBIhUOGvWoPpXjTRUdWlzIDqgdxiGwSZxGyDeEFYmAZHbFkrnjiYiBIhABbaTCU3dpdGNoIFNwZWVk'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mRmagDXueTMKYalHiitgWKqXJMZjMtgjogiytYwRnyzoEumkSLJPMQVwzvtneZXfahpdyhoMAKhJGUYCBYPTkQCdkhXCFCFAwJdvWhbeJYtnyJoNZhcumDlefPlzdImOEJZtOjAAgrpLWDjiTfvIAmEfFmljVdAqkmgxrtZNNkPwKPdEWQlqWYDomRxuUiOuddcjsPdSBXyejdZaTrZMzjRWLklvDwARjoeTvqzMcweGwiJXlxzZxFxlFjEKHzic3dpdGNoX3NwZWVk'), 1, 20)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BDnqWdFfpqaZJSjmBDDtiCAdEziaWGNtSSDqPqDVaFmDaiLUbXkaRsqKucKTDCZgmGefXqUsGtQFfqIwOjVbtFAaIVvxVaOYVJYJRJFcVDXXohxyCMEhRnuKfvJVRhPZXYgoHzYXNlmYBEuKaaNxFzXnofrYIhKpSakflKfgJnOaCObxjYrKYEEwavmQeNMfNVaOwmsLMXjkxixcSANdKJEtHgtnXyCNvvkRuMbgfIocBxxymhQVPDAqxSkpYikc3dpdGNoX2FuZ2xl'), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BYdfXhdBzCfKIitXcCqcwxDzLcbbeaqNjTIpIOpHRPkskAoWCZPNQFPupvqYvCFfMqYekoJrYPXwzHUyeZqVKZTsksHQgKyihdBXsYlzyjEWNskMOgnBnzTkZcKyAzLMmCTqXBvsxVrQjUDdIxSEAjhAnTCLwouMSRsHdhcnvcATmujEZbAemgSEUOqzluffwLqNZKbBrdxQdnuXuFNoNKidVMostFHjOAMbuAvmCGOFImZEfserHEYhyMjXMSCU3dpdGNoIEFuZ2xl'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mJwNbNrNFmpJDkRsfjCrhzqqoCYBxHVPKPvhmSetKCLCjeoJsYSXFRjUwHMkjAdAEvxzUfkbssKihMXxktLNHNXufHAjYbZSpTrIqSOztCECzWAoDbNGPZCJDKYvBCdhQXlwcBdpDwsDpqgbLPFrKXmFReeCmexYlufXpQpSzPoknsDzVTbhezjEAJwmsngwCuMVdhybzMSsCEqKkiHCAiowNiCOMpQrahLiBTBGePKiIxBbqGYgrrAUsKMvnMAc3dpdGNoX2FuZ2xl'), -180, 180)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ZWMWuOsCUCmxhkLXXdSHoCSKZCHpThWpvchtzcFVveSTtsmWHQoITdYUfajthVkLgHeUkaVvDkRzweXPECNXTKOYfeBXbcTdlzOdpCBnKyGFEaEZcTDuxvnncbUjgHCnTadQbziUDwOvTjdZUuMUGcsZgmyScOgILeewbflusZBKiNGFvKbNEgYJzZAuztMeAfsjITxGXdehDicWFqdZWJZWVHzaRDXwlXrdfoUpKDDLfrKMQuLbohsHcAXGnDPc3dpdGNoX2ppdHRlcl9kdXJhdGlvbg=='), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fuPTamMYsvmQENNQGtonxKdQzxHgybPCDMctxnjelKVgHIiviHVyqPYEejfRkYQZmoZjneeWttDYtMBDAUGwPzLFZlLMaBWDRRutRQPZsxaDflNWyGagJBAEbXynvSMyVGEInPDPmQRFxJGXaIETqxmxAXpkmIucSmwuklsHhZioOwSuFAqPrtWxxnTWDNeRmNkIWIeKJuxqtpcUgpSoqopSGyDolGNUBTmvGqeVtFhpObjLhnmTjngKnrBmBKGU3dpdGNoICsgSml0dGVyIERlbGF5ICgxID0gNTBtcyk='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jiGqAcBgCcTctQhSUdMAYaRLCnycvfVomogAvYXWtUjtmynLQEIePZYStLNLcDSTtobKraGBIJVBubzeuxgHwVhdzHOqQtPeGaSYXIraHRFwMtqcNNHTzCuuMccBDTrnRDFyjXlscklsWlFvwMgSVQMydmoNvHAdVgKkTKjpimgDjbfgMsBbKNNcVOYtzwABHWcShhwFDBnWkzMcZwvYGvCfcrOahqojuadEujVMbaXXWckjhEuwYLfeWxhmHyOc3dpdGNoX2ppdHRlcl9kdXJhdGlvbg=='), 1, 20)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GMeBtObxFIETjQMXjCDLNGMIKTXCcsWmIuFNkfimvXsqHPbjMvMqFVdbnvLGJKtMVLFJeYBZxpAfJTnkWTgbLPYowRIPAsaFJdpGZmZJARUWPrKcAWxSybnRJSVuRrosQVgtyPZQUbaHDZDPUHBQohvhpptEhUAibILgvpWsvnzWpbfKjzIHkUGLQbYPRoBrXrRgIRvMBOgufTEELlYOyyWtEyCMqcqXmYeqhLQKARZbInAWzaNQGHqCuNqykdEaml0dGVyX2FuZ2xl'), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('MJqTWciSdNUHuvVVcnLinlgNQlmyzqZXnJfKIwLNPFnalicklaBleIGrFEWWWsHINoABGhoNGuhBtihRAFAvxWJCzTtfMxfrXaykkpvZMirZJuuwuOBQGohIGEGkWZJOpVynGHzaGhGGodaLkSOPIHlJycXxZZKoAbIAMuLbTTOwTjQbLtiSuXjroNanVyGBEuTuTbYBOzThKwMBkFNhCRGjuhALRMzHgXtOgjlDpXjEdoUYwdBJFSlUCCdsgduSml0dGVyIEFuZ2xl'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('grGNOUHkqVduKEPznNEOcLrmlBRAoOVJgbbzKvbeXLpmAqdnOGWxnAahBdYoaLuYyMUgJRFqkHaPCAkGdVlUdlGgqaaIDECpxVqYnMYQsmegnJDKyzCdExIgLrlnsNtrqYUkqyDuRWOsnBzOzqeaUecQwqhxtlZqCCFpdzOIYPzJezYhHrNGyGGzegCfHkdIOSHpnhEXvHTQJlxTtSEGqUuioPDfUIIJpwxEfFOFvIqcEbAxvYlVZHhbSiBKNnLaml0dGVyX2FuZ2xl'), -180, 180)

menu.add_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('iFKxsxRokknlvkVZlHGpuoegsrGbojMUAlgIfyQxWvJWSZtWthWVXZWYSMOHzzPmJLkZUcKSbpeLaSXzsoDYvGkAzqIIgqVvNazEAtxscbasilgfPmBfMhgppIvyTMNEiwjKOenHPKiFaynCSAqIqvxGAWjCVgytgFUYcNTNxFNdbMnuDUSJwuBJJWvzDPdNrsfZcbOWOSGAoReZhEjivnAmDFlqPDLBNLrQBKeKFWIBNalhXEJKnzKRrZntlOccm9sbF9tb2Rl'), false)
menu.checkbox(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('pwNcJtNiDHPSvCvKASSmUpFzISVaIduPqbhcSpjspiMyfAnCmYNlFmcpanJmIYjeWBMOFHqgQVChhJjAuGHesohiaoBfmZRqAkUYVRJgAcsdDIyBXfCiRLCpdGVYFriOZRdlCjjBywkXQpLjBnHnYaZimzRbPnNBadNjPdlPCclugRdFUmQKINMrAGAMetaviZnJSJqEJmYSdQlQuLqFdpXPkPeCKBESLEFYlNuHvToUaBWvNaCeIOfRJpnSgkqUm9sbA=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('PcQRsEgJJTEkzePYbjkKxBSrepaiUJLgdQNXWvnZYGIDSXJEtHSVjTOYraUeiserNamfxxKmjfXGzINWxFCNWuMvovVxDHegzVIwCLPJHsTHfYYCoaZVkYtneoUWXrDyfDUrHplHJcrXxJbjcJQdrLPknLJYdVfgLonVSCiiEEKLMjWZyjhvtTMmhfXTzgVAOiWAjwEefpuGHqnDhVMuSvSRAKnHMbCNhAxIYtGUBIcWsmlBENBAFASqYSoTwZacm9sbF9tb2Rl'))

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ZGXmgMyjWTuGpaymHkHSCmZiPkCYVDzRXFxQEgNDTWrGELTuheRcoUxKhfRUSrlbdwaHoLGmPRpYVNYBInHUwOtLhFvmVQSWGyNnRXXTflApiSsbyTaffruZyJTxqlLlAFVIqLhvgqCpVoNGztBXTrSYgfdCdsYrYvHjPvEpuxNFDtknhrPurfFwIuWtMQErxPwAiBejRkvlNMhnOdjrGJDeZqFoSRillzlQQpyASPSLQJVAcIMFHrhIynvdsIocm9sbF9hbmdsZQ=='), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('tBrhrHdJVBNXcIiIvkwXGWUkzCxLjAFfNvmsySGzLIczVIxurJUvkaIcfixvIdbuMjBCCEmJgpYCLdWCmZvGBLTSnvsxSKAsjOEMaDCNUgNWYIymjMiNfvHAgDGkDsIfRyVnHnwLvWhPOJEOsXTihnhiyTLQBbcLlZdrINvpMaWGHvEjFengDueVXHRXzEXlwUVNbeEXBUnFVTpQkcctdKscrwwQMTFQtTYUElfWkElZxkXgMCbwjbbwIWjTsDGUm9sbCBBbmdsZQ=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('cMtSkBSFqpyjAHznbgppEoHwHSfrEByBgfDZRhxtTEkSJWNBNxvQEUlLHDwQNMkZkuPJIkfhdlMpfpFSUAeqXOSUTWLWWOoXqEFbITcnFdtWyeKeBZEteAWDfZSsEZdhzgaGTFvHKzNXaslFvOrhpBFIhUnHZPxiNhtTKNEwDiUnPOzkrSlbvshAFmttxoPzIcXiMWPiQywruSubQPWmwlezzxWNFmrhjUbrkaNRhofgLPmnuTFukGWXvdFnwmucm9sbF9hbmdsZQ=='), 0, 90)

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('iQoiZmqNTCCVEuHpoETUoruhqnkGPdLLdkrHxZsGQTNmBlxzbrSRnZlQvjfWwcRqCInmdXdTqhIZrViPRdzZbjCZTRMyDZpPoWUPdyyxuHPxLZzAQveqlxXrBsrdAyzwtVraHgSsnmWgqiOHljefsjWqIqFLRBAmoXyOsLtZKIvywHPwwJwxCuWKHqLRTjYjmeiGEEtsMRFyYNDBtiSgwQdWQPaqZzsTgMFQUcbEeZUjJFwNfKPJqZWKQiYzoSaY2xhbnRhZw=='), 0)
menu.combo(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wFKuGWRlLTUTEukLwyDowANNlhooWRqeHXujERNOWAkQSsRbzvgezNiHqwGwJHjcidbmSvOmEXkcJidsOBarTeDuKypMQOKHiJkjFxdzqiSOBzwbxToTFBgPhYGDRXdjzApRnTjYrcHeoqpJfqehXZExDrrsMHKsrMdLbgymhizuOovKqzlUkhmuBzyxSngkhYPCrBEeosNMedNWcvSGcxAWvczhSpHhYbbVCYkDljkuZUEXlqIUVmIEedUnmgPQ2xhbnRhZw=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('waZciwYVKYcdeupkLiOTSEDatNLbhAhXyXatnlVUWNGorylOlSxPmcjFqtUhqsRoZsjLpDtHadistGUWrEWnJztEToCuBzdyTSZSeXuzFdPYiivuWwYwgscAXrOnRpizauzpRuqwQGbXjOoViYizYqhahybLazRwgybmVmWDOJXzjAjSTfuyNsVEZAEFBtSGFzDyFlwKRPUiEKvgbBxWulziRLTymTjTryVsIffIwzrDfkzzraiodDAjVqHcWrfY2xhbnRhZw=='), {KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jaBHDdnIFUnPmOjgKrEJyxiBEZamUboYMjOJSMoIuOuUTtUczNoJzhjWOAxtvRBprYmdGvveYONKlrQgcWSTGzmCLoMFcKXLWYOcuZLFRtbJCOmoQOznzEWtptMMuKUYfrWAogFChSYWxcuSlRAZgfCupBnhcCgatCVcOgNVVmrUTIBHtXehDBjXIiXocRoaKRqAMWdfbootPOHgJmiesSkWnIsCVJxGoirMCElNMKjOSRhvffRLSLKAAdRUpbUT2Zm'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('rrHrMLZGoUaLIhyAhikZSDkZIZJtYBLidRLIAkMmxdjpXQDIiAgcDXMeoZUvlqWGcvNgRqZjfYGtYjSQRFonioPDBSARkmoVnlToUtrTNDMYWWtvZknMsioIYvmiPXNyojVjjHRaGEdlQyLJNutqiCfLvDXRcitdNtXWXfwpGcvGYwgNCLpwumtqQmDYwjeVSDLSQacodBCycbtejWvYfEBQJTEsYmrxuLiUaTvjikzstQeSJwRtHccYoRLsFNQSHlwZXJZYXc=')})

menu.add_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('LWmiQJDUOHMzWONEjmPuDCCLasrdFUnZNqDoYxUFRihAcgbiLjjWrXYPyqvCtBCKWXTpMJkTGESzwuDRbOPXWdfBoYBRCWkTAnnGqIJbJDnuxTEjFoTMxKvzhyitajUktchYJWXdnnHXEwAzItiwRPiMGdveiywXGQNWzRIqRlqIyzqWMAobfclAGFiYEVsRTYtxKSfraOXlEZAowbVcJvabJLAxbiSMkoGOeBsAdgkRqefRZIFlMOTPVWtyoIVQXNwZWN0X0VuYWJsZQ=='))
menu.checkbox(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('MfdzBCeJtFDbFVerAHEQphjlYoZUTXvTLQvNenptcPMJOStzSVRXZQaagXcFWHBMbnMzkaxkfneNceOedHXlNOTLlAXDvIPVDXFccHrpeaWMqQURlifOOEVGsZgFdOAduzbLBNLeOnyZwcynkVTcVzoHBiehSoigPdnLKIgvWWagyTzhUgKrgzfZYAriFWhUbYCWileoQLXdAQgArZyjLgNKgpMGXhJsufPMHvPisyfURFeQKILYrdSXfaeFpEkQXNwZWN0IFJhdGlv'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('JRBtrffaddKZeSMmzgRLkmBpRIVumBQvlEmRjdrxEeDfRpBvVFdDIysoOuaqlGVjgvHKHybtxilHSXuiidxxRDCLzixRQyKfzJlSGUSuJdzLdISzwFLFHOcmPKvwORKGYYlHgHOrCONXbzRhgmqeOKovMWtOQQhlriUhDoFjxJMbcbzVUetPmSNeKPVddxVKUkFLFNetaJEbiryibWnQgUqRInuKoFAMKMfCikIuIoVFXFnQnWJEXWDvyqNIpeLQXNwZWN0X0VuYWJsZQ=='))

menu.add_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('QahYDmVxUGJQIQjjucNNFGcuayCZWIdpDpSLHvZwflSMfcUDLLrEQUQsuwodcyaBvpSYTiEeHDngstkBSVuTLbBEGstuEhkMyBvtINkwhjRtkRTsIMctbZNoUkoUOpQiHpWjdqlkhhozCDSgZtuGNHDfqDUSyjCtTmqPtkKjtbfFsVqZNAciRhcWslEQfqAvNEfCIwaleIJTXGPzgMGEEpFvgodhJdBlOyDmzFexeieSwibodBvjrqlNwLScbIqYXNwZWN0X3JhdGlv'), 0)
menu.slider(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fxbiqaQCkUMcODkzVgSxybtsUsMDqHrXOJxGlKYbBMbCARxxYdWNouCdalhshncMRyLMVkNiGdGmWCfbKYLYnuVWbnvtCtFRLMpFihwGTrukjstozSRAwYZrpVxJPiaJuxNrADewNGQRDRMqRCKCuOQVUogmcKpKatCFfqUmQZgkLZclXySGHVPZYvuQhwjjtPEDSOtEhngmTHXrpKcOxSrlLQZzCKNDaOZkHnkzBrpDfxqHeIjwTjPbVRJoItbQXNwZWN0IFJhdGlv'), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ITennHvFhuUAOBiRVsUyccjJymTchwMBiATeuBRXtmkrYsfYgKriiuwUvUHfXcwCKWCTcbASSvvdOJFmLvmcGVDkVNpRggRuudDWSefzkixgbjAGJkdbyrGZVGYiouDetfgojIiCAnMOfuFmAxodriJwZsRIWJVumwtuAbbQufKwTKCQNYcQmikEufaCNVAKiBNNmtSPfWqxjzcCGJUeTgYaMjrmalEcXRmuXSHJZfdHvtLXHgLsiYNSYdeUcpzYXNwZWN0X3JhdGlv'), 0, 1000)

local HyperYaw_enabled = true
local PitchBreak_enabled = true

local function AntiAntiAim()

local AntiAntiAim = menu.get_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('JavwjXvkEuLxLrCHzZMvnQkVFYqJPdcKJiwuVTeDxgkqWnuholZpRBpnSJqCNAUtUQqtjZDiHfdSeyGvDbkHAVQFxipqZNnJXqEyupMCcgkoxHBisTEPXweDSWyjAzhsyKZPdsHEoLclXBKCUhaWzjLGKkboNLJjsPfVsalDSuxRLWGmOJpZXpRFFFyHtPJJDGGolPvYiTqKRWNkbOQIWPbUFvPlWTsYRjVkBjfCKYgjSfctkRkIXZUgpWiKXPCQW50aUFudGlBaW0='))
local AnimBreaker = menu.get_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ecADmxqlJjZQeiCoJcDjaJAXgDCaQJmHTOYkjRczwKtiIgWJyltWSfKAFzxdxTwTEkeNDKwIXkEZhtTgyxLhBthdohbhpGEsxnysFtQYkUPLpnwRuFqYKVJIIKsRqdXoYnxRWFbHAPrJvSQjtGxKUvjnVNjEQJArsfYIWFzrQCNhwOXeBkfabvgykPWiYnHoOPcyoUlLlyKBDdzjmUyOtaGHqhGUHNqfNWfTxWkrEzIhdstgmwvBahKVqOaRgloQW5pbUJyZWFr'))
local AntiaimMode = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GASkiiyWgDNDOWoVusNJCZlzJKJowbJkzWjEQemavTmeTKAikQCaZEIJAudtxuYfoCxDZUxSxrPzAzGFINNbCpvkdeKLPvXOOTMBvuTczXZBTsFIuACvrtbsxWvkoecZoCFdZlmLcJYTUUPrggECqDOinSTHaRUpzPkWxThpdGIJAkhuUgRAXfjRjwtwPkSFWrsGMYhvFzslsbNNLWANiPZusTGWEXJsBAVWpVUimsQbdFdBDegVRECziGulAXRYW50aWFpbV9tb2Rl'))

     local yaw_value = 0
     local jitter_yaw_value = 0
     local pitch_value = 0
     menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('OLLLcBUfbLKGyRgIYmtPSEqJNTDFFZLlXeSNpKrFvuWEUmYseGDlwDFcrEPPysVUrfudqGKYLtxcTMOKFjAFKYpeNvdkqygctOZHjsdYRfHAUAFKXWCsqezAWKCZgBoTTiuVlxvfpwBQQxmKMsGXXbezaKkYFoseyqUtEythymYKxOzOHllKytvWlNmANscLnzjzdoVUeQYTvFCcyzwhNivAPpmlreTjXuEDtgilBVqeNVPdnQMfGTBISXtSLgaYW50aWFpbTp5YXdfbW9kaWZpZXI='), yaw_value)
     menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('vmVHFQjTQlDGgZxEdtDucGljMzwCeFmFUiRzUQgZaanwNYONboFWPbTcfBAqXMEskOQwNjNwsrTQJozBWoOHpLnuySHFTYpdjppAfuVPuDsCdsLjRmYazPyjVPcNroGWOfJvizAzLCrzcGxEcaGzXgjnbpOZDPEuKwFjsfTNeZlAJCEsMUFKHAbeZxKlYEFLTdobobEamYbITJiLdGhZuuUTSkZkSMVgTjEEMklmiIhuDbuWhUBIGOieBpDfqRyYW50aWFpbTp5YXdfYmFzZQ=='), jitter_yaw_value)
     menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('hcBvZvHPQNFMUmjRaRZaydTCnsCueEVcymYmvbpAtpZHeapjykqcoYRyJoMGZkeOMPfXmCehLhUEQZTlrgBnboXkgWpmyXLKLoFAhksBvrjbjnHxdNticIzXnmQKRhzKerDnuhzwSTCDalkLFfESMstIQmxhDOAmKmktKwPezfdslrQxFxnaLMywytdDnVDoKpheQhDZgrLAOwEHyhThEkVkvUGLiNNrsYGQvEmioqJEfauhASTmSZSfYHWowBQYW50aWFpbTpwaXRjaA=='), pitch_value)
     menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('smFHGcYKhMYNYYMhKveUOYCrEpslbqzcWGMwgTPNUorqSXSCQmHsPCeNQNBEUdiXAHRwWcqegoxiDfDQeJUtRelGIxvPasaCMHwkNeTCyBlmvZNJpTmNzPZrKdwbzEECDMmRXAACZFafVHkltYyKdgdhjyCOIXtTcUrbFyFUMVsblEXVgUTBhYEgZvbzgsIWhSBWmXFPYXlwxuUWXavrdcxlyvBtveSebWhEGGPSbtFqBMlOloIsbiUDvklMeClYW50aWFpbTp5YXdfb2Zmc2V0'), 0)
     menu.set_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('zqLCEeYiqMxDmLGtYeSatcqcbaYUrayhCHlVceqeoLekWhZWlKfzMfTrzSYiJntLZoOBWVauhfWTWUtDPdNFNjsNIEaIKVlzBNxFqYUjGMRjLqaMHixqisfWXcvVTNHzAjiFaRJuPrZMnhTtAajgCzlRcAfHEHwXvJgbJHhjIDXhEjNiLiVUCMimhTGnRciPlfmZFbHtDPYXbhrJIPjdwoEVXxWnDLhouvJsZMXUFGBhrboxxoIugyGFSTsoEzDYW50aWFpbTplbmFibGU='), true)
     menu.set_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('DjpJPXJCGuHYchyIYFcAhAxIuTrUfTlYUohaZpoznZpBcofkcAaUeeIEqXjyYcSSBYVlzVJzMhAUFuJxwJRMTpsfGdnTAtBjjvlxpOurzqXaHPgAlwmdwmQGosMfPluFVcKkbveOKmhgYLKqHlBELZxAHRlorAushQoahUvtZRvKbLismflYWuOJuftImzDqRWBgvvJWWKikodOfzzrHgybwLMJOKiCqmTFxTqsgcDAMPkUsYMifwqTdcqrBCKoYW50aWFpbTpmYWtlX2FuZ2xl'), true)

    if AnimBreaker then
    local break_value = math.random(1, 2)
    menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wJSLAadvyDdbUPahtxrdNvpkvPqfSLNzzBlUBpNvcAuXbrpNEmtxbMAuqTsHoazOYAEjwKQjPEdVKKcgOgndwpEMvIbweZYyfJOfZeTkLuIOEKIUozdjxpyOsYDQEsNQncBLqACnOVAaPQVdOGXcZkUbLCcUnUWuPqDmuJPIcBAqFnmeQFSamqVEnbVWVWQlrCqnSZbkWmyZusLXPptQmCFwMmvJOkpkWvXeBlncYVcMqvsDauacjmLloTvfBebbWlzYzpsZWdz'), break_value)

    end

    if AntiaimMode == 0 then
    
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('tBDkouLZKxkCRzLgNiQZuGaSHcBumeMAUdgsSHYhidOJaNwCHqnwthxkRTeAagUXYfNpRiTxwxSAaJrgUFNDzsZUTdYeJuvxpGAthoYwvKREPuIgTYZArDLaBAhBdqUmZqNqsePpzUtdDMcxviXDHfovUjNxVXeeZWNDmnUWtuVxjQGrwBpjbOZmtkULyWpCiNgPPUSVpYjFHfIyJYHwADDzFKsMbrJVIRmhEpXQNXaJREfCrqQZJZnngdkiTUBeWF3X21vZGU='), 4)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('GehAidqUisYHXocQguHrodtSKxXkioiYRzgAaUGNZpOOxMWWIiKdFugMDXIIdTADCScWdmjFkKafBPQkubFBseaUwKyPGZkEwSFELukhgzAcFRQUhWmdEwomsLikXuJYWKuJWgzeKWwfltLsyEQAVugBvwZUUnvbwoCvfbmaMveceeFSLTUTaeZsvdiOxHDUGLYkAlMPahMCeszboZAJBmtxfyOrXAKbokuYoRTvVyHnvbksnROHlqCCIleNMdNc3dpdGNoX3NwZWVk'), 14)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('NCnbgLRaPhnNSEjbbspxVWizSsrYxNDHSONQXetPULtPBagqvmfRJNSGXUpRvdeeGwwHLGaAawlnENSRMxMpjxfSgjdKCvNSHKoVboOLwyBgKZlZPbbirdBADJDuLeqSGaBqMGyPziqVuQmaIOabxyomvMQGaGeujSrzHyCwkOjHUUwbTITERyZQFSfAaiZiQjsCdFmNjsIAOvxOlaSzbAkuyMQjTqkMpQwbrUTJpSxDvqIlrFWRidbbIOtsOHzc3dpdGNoX2FuZ2xl'), 30)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('sJEupJpSIrmHLQTZIBJdJNSFpCyRpIzIpFHlwotoQDqjYRIuJMGvMXinKvwREKPVAKNjhDPgNEwAkkqppZDgIziVAYAcKKDLcsQpQxIojKxaKkgjudIuXCfHIiuGNyVJVzdhqoWmePSqEIxrtzwHCpLryGPQvKiUfbdUGKQEBfSDmyzGQBfJGFXZQiMkzGzSHEisETDXxlDCgYanYdOjutRtKcmrlNZZSsLufNiPimUnFBeKjcGmwXtrIMVtxmEc3dpdGNoX2ppdHRlcl9kdXJhdGlvbg=='), 2)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('cUFdpfMaWkjEzglWxYAXvWxdLqfZdodavHRiZUavxKMDXhhsDOuEoKGvnKkSFcgLrdKeaxmTmwxCWgauBQHoNnVPCwRUjYfKElijdbguHyhLvYmgLolDHFcGEAloyzngRzrMSidJIXIEiGpEmIRxPStxCYnlyTxxbxUcUwSsdTDdISbWQrPFXTsBIhxnbpENwOvbQBPzExgAqCXkPBvKlexmStoksZkNkjqobZdkBufyKtLVHAoabLkTNPCMabWaml0dGVyX2FuZ2xl'), -40)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('DbSMThtkTfggidImVdDXVWdDTUJcwVppOovrhwqNRyVJKDwoBLIfNdDcwiBDEKSXemEUgitMhKiIrgKbgrIZnKKwEQALvOIzANkkBvElQBrIgxUhzyJHIJTMZwfpKoJMRLBwlRjEfRCCKodbxQQOJepceDXNEGXooQfYrzSSBcTzoIQRVVtZRTbjnBrexKDjFQiYXizkxKIYdraTpAUqnYOtMyjCvVItmVMUSClycFecxssyGIZPoVuldFpOXQscGl0Y2hfbW9kZQ=='), 0)
        menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('amXWHFMOxYOqLsonJZaFGMzrfPeXSlQYcJMkMNKPoONMiCXmzPcqGFqVXtUvlAZxfkZYvpbwYWJDgVFTotVNFVZhGaeDFSOQjocfqUUPSCkNUEkrGEdajoqjutScwWVMeqWxlCwbIbMQwwTuOvgDAdRrCeWDnmCLKujGEfkWqiMyDDbPhHqnLBkZnPKfxsoKQohsUBVgMRRDaZvVLZmypGdWAyVpbGeMUrTiDewWWvRhmqGxrDZkODybWuqNanqcGl0Y2hfYnJlYWtlcl92YWx1ZQ=='), 0)

    end

    if i_engine_client.IsConnected() and i_engine_client.IsInGame() then
        if menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('XRkvNEMylKIIWZowrlcXNRkqFucwzZcrAuItSJPITNWrOlbrukOdxPVRyWmuxQDYTpckezYWWtSXFBVxlLLZzKDlbjyJnAHXYbqDtHYuWKgXVUseSISuIaLQprLjevsupfGjnzjjpvBwgChyrRsVDQPQNkMdEfFcoDdwYFhepIcGMOWQpVwHkiVUjbiPaognUixkKtbBKTcsXkRpyMEhfMSjDFmSpvOdCrquJtaLmbBEcsguCJbIDoNIAwVZUQdY2xhbnRhZw==')) == 0 and HyperYaw_enabled == true then
    
            cheat.set_clantag(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('tmhimVLMozJHKiuTHJTlbmYmaTsLvgXUVgcuBvmPuFNroDWNkgItzFGAqsKLiYGbpeuzEUdcsiYREVBuVDkFDxihJxlydVdBJMVIefcTqYssVbHFzLxNFmQWQtMWhxhMsEkfoGjMaPKXkonZastnwFvmdCGVpTSnMjbhytBaWsMyxmMMrTKVDMZUoUQEorlsvBMlwbhXvWxWYmcPeQoPDlRgAqnzWGoPdcAQaSevuSPjzbSZrdkWbiGlDdbNfHq'))    
            HyperYaw_enabled = false;
    
        elseif menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('JcpqWCuZDILIQxfkyYvGdXwZAzWkbGvYOpDCvXxKAYlNcxwHdVaAHmElQrsHbzODWcQmuQMjChUUaOLAjIazakXGyfFSLGKciVlVrSaIidsBUyibzqrHseJJKrVOqdUyACilNBwFJomxMVdEcojBFaDrLbzJQZUBenbobDQLQuGEIsKGMpWCAORxzxGwXDwZgVCmNHEfSueJHAzYoQMpvKxYdTRWBpfzTDGsHmBFbrDXVaClMquyyYvRUAPPNCoY2xhbnRhZw==')) == 1 then 
    
            HyperYaw_enabled = true

            local clantag_HyperYaw = {
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('EHDnIMPFAWAaNKFultQiuSFoleFaTVSDKIFRRwrBzcroQhAEAQfCgXyRIkCfQNFiwkdpumifSoAlwczYezXYWgfMqaPwNEqHhhCgagAFgphNvWvIoGKkXbqQzNDgiSgCYnjZmcmDklSGBTlJeDXlfGDnWZJpPDyFiegGaJCslJYUuyAEKSeCgDQxNvWoPKOGmHtiyObBeQUeFiMmKtcBxLnJwoMhiJljjVyKtxqdUiWDCukhhHcPceIkRzabbTJSA=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('pbMpyQEITogRjGJtQEMQnskyBGAVAHMpfBRhFcuIzAVBudiYrPLboWiaAcXpQuaNlWsCLnVEcMhmPRqKUmViBJXXhtfmyPBzlzpThEKTTiORxPuuQKkpeFfUunfzbGyvdyJLjvfGDFqdbtucWlPvSCYnzwmXyHfdyMVVpNSsLcOQaChEnjgTCKoTvkJuxtAPniIlatlZuVNuDHcXRsjjjxcwxFEgtgrvjuqbYAakanHTvEutfjHzgDVDooPlrISSHk='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BHEIwSJiFhfmohmvpCcnARlToTlnZDVnqitHxWXgRPnqlOtZLixznvcyQpalmKaNFLLtYfUevrWzhMcZVWaDNCANJjccZtftpQRojNNMRSxOUtOFVIxrIZGwYDhaoAfnqgIiJfZpKvFCwJEWhNuAKUPOcbawSZBNEsCOzMYAHJQMvLKHPFcKwEUWxIdsWEIwyeqzEucIYNnRLeCpqZyHgsvejyMmfDsrTPRwYSFMoTIUxwdtkmbnVYHNUppbSMBSHlw'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('LyxMGpMVAGioycIQEWMaqBLZjIKukGHRLrswmECRZxPxmLDADOfFAgHAiBWolBkEuEGPZSSlcMDgWFxEKqxmxaACNjbgEcvRiReRrgTAkMIPdyXGsfPCqBDmsqGWKkTgfKkwRitVmrigXlTAVihvOQYCUYLUhqSGWqRkLXedALuKMHGNgQcCrNkiyYRFoUilUNffFBHfhieErtZImzwCSiyeWWJONHjqUvuaraoXuUELoJmBOBFNmscqfPEVumVSHlwZQ=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wVmoAtnhHfQSqpPdCPdIqiBihFLAUXjgGNvMoeHKtFDqwykKVLuubmRhTcJSFwujaZvtDxgAISBtLRLgLyQUwqcqaahQbUdRmcwkTjibGBwKKxOacNlzKFnlwDkUwnoQqDgcrcXkyNcFKqoygMeZwPxkXxhNYdCytVkFjwHKNdafSNwuYsqKRRRGmgnoBeTwYfnNsyvfBumBGUZPCtJeTlQRvKRPTsBrarGmenqDcXBzQMNlMITPRLyhAoHhQtUSHlwZXI='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('gOKDHlScGAqbaiAxexcGzbpkEmFBClcPPfjlBLCGuqlwUEbxvjiAxqSVbLVVgkKvnElvUMKUqXhTAagLhsnkFVZdgyURxBjKKvEONrAeEgdmyQhZttpGclOdXhKAUnvXelFYAyPLKnFSvtVNdoQbKxvUXRocHuCdsUzKjLCasoppdwMMxNvGuQeKpSQPkVBsZXSXEtvvLfFbEfCOZVrmdSbinzlzaGxLanIbWodYhUaLIRlthJKgQgWKYPzYMKASHlwZXJZ'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('tlQTnNKiJLGQuBqwQRxZBFrYOGqASxVRwxNnZodcsHGyFJbzCEJAVvUOIWFzYMYHTviepYtEFZHfkwYfKXXeqxqHMhTymrSCFjqxEhgDrunebADOvhuptgVvgWxHIyVKckmlhvOpmwitROXDvYdqHojhGxbiHarMxGmAQqWmssDMzKiXqDNLKnOVfWXFVRhCbRaaMYSoKrudOCySXEfEiqmgptFlJiLDuQanxHcIaoxIGbyNcFfjOFsbhLuvgKHSHlwZXJZYQ=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('eGrGEYWObxZqdhZGdxubyvTlreVzePVeSwUDsMywzLuFyUlwTUPdliVwcLftjbuJHzzqTJlTGPAqEVrpLZtCqgfpJSiaSFHVbectNAXrYNOplDirWZVbaBZMGhrwpslaYlWfVPmkvuTHskMtiWYNfXltHFDLfbrGppxpwNfwUuxKNrZeBPmpyJYPCeBkImoBPMqAZHUAdJFOMSDACHWjvantExHQaFwhazKyeTJKRmqCiUtTXalqumfsdjNKjVLSHlwZXJZYXc='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('oWPzngIdivxbqBcxyGgmFMRXUGGqSYFezyKsBxcAUvFvxLORYmvqsaFrVvLywzjBGqucoMVvbmIAhxvOTzuXGfkodTmXblYwzEojLFALNGouwEkfDIMVTyUOfazLWSiybCjMXoDgWBHHPUjuFGmDMiBlJPONSOKOxPnvjcbrygVpRmHkofSuLfUWqHGGCfUbcAtuQiUbORNSkPVUcquaUGJsYDSmMIdoOUXuxrRgxBFNZulPPcHeIFpeHKACoAgSHlwZXJZYXcu'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('KwJrimflJQdrTGTeoJGxDqWjymzOVHKGsEFvlpNvHNWGAAkKjxNlrKAqkmIhGxAOOONPlieQttCgHLWwvyhBXAQanzfcEIrFRjqhndqcErqRPXmMoQqDBDcEBPZAnraaiGyeqVCktPZlvZaKzDPCAaPbKVTZDLphQXTirLBJEgOAlEsntfSrxtoDDjWLCqsJspEGlstpjOWmHZzWJsFVIAAchthstmwPUcrmpysgxjXpnyasUZoVJCVKjepLPLRSHlwZXJZYXcubA=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('CAMmUNmBeUdSUxBBIWdqzdVnheUdlCICtyKNBcoUeYrwlmOuMDRxftxzuuqEpdyLcoNdxRGYubajpMOdPERFHVZgfTagmFzHtbRfhpdLScQTRQMjGFZZrAHPpxlSZLWEWtjrwNCLvmgSmAoKeNIHzSxVqRCumLxBUQEMtkisalwyQcqKJyULZofPkuhMSkStxHBjTjFeFgKwgnzhSaRHKAPtmSLCtUUpChmsKjRokAVpZhWBBmPCDjwwepiscbRSHlwZXJZYXcubHU='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('XpynwVzbzHKyYXfwYweUisdAlmKfshdBAKAfjHWjVDRcznUuOSmOvpNALuNCeFnMTPhipqIqHPegvDhzmnpFmjRtbLtMxYjMEAQTfwcIJPDiSxOeCLxovMQgiqcCgAcyvLphUtNAEmDnPurSiMIHuQhcxhiHFnMtgJHRyERUIVkwQroIKiTsvEWdpOagGKaCyfjNLFPkTwJgqXispKekdUaZYaOreULePnFCIaKbpgzmBwxxUcTEZieTyvcBFVvSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('kuyjfhEKShYvgAlShZdFfRpAlZHDpVsXizruBsysZxvrCKtdvYAfuBlJwWRGlsaYRiFyEVfMYTUxhezhSJtUGJdRYMLvTkxeQmxkmkHFHrJWlIMLhIKUjAuUQXPXgDoeivHXFxkxdrpGakmmEBAdxVKLOqaFcZZzqPJBYWwXHhLCuqnrTExJKPPbSZwuFEatKDXpCIpmBvHZSpRKzostKJzXqEPqXzJbfhZcAFjUsKzllqULGZGiFWLiEWQmjMTSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('egfTOHzcJBscQyKuQIRPULSWlyfhtLwjSUPymMghevOtkDSrlyrMYjltpkHEbXWonGIRTaGMEzSgLMqCcVfWwsncEFtnzHXwpLotVGWYOPWRzAlbfmxHeZnLTgDHtQUgTTEvPInURzYHkUyHKjIPZweVQefBSDKpRroFwOBoRRQefNNqyLKZOIZCQdJyalCmFtSEywuugjcICeMfRHmxBOeLtWuTdUUXQxcHoNRsbsIYhvWXdrzFubLlXZPOGfwSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('kdICxIkRZjBwVNewpLZTDJydKuhaoeStGBvdBhqFWjUwqHKrAcdhzNsRDUqoRziGOtBILxZrWVHrBxhquVXcAqvihElzKNIutxjJTtZOkpvGvoXpEyLfPEviXPXLqVoDMfgSgoGUPAhBAGsfjbcxPBchtFlCeaWqtPaQEEDMoDJNREkyLNoZUbwHEWWTitFgyFlihANOlSGNohBLlNCFyPFgNrLIYlgwJvwbpjxbyaqFIODmenEQbClQdhLtizrSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('QtdDTRnSFFhJoCmFWHVProfngzcDfFgWFhBqVidIwpCbqnuCRbJwtEeNkHmkThTwaryuqHlBIHvzAyyrCLDGFZZUbtMSbFuKGPRVpJTZlqwdaQSDnoAMBaxLXBusZnZjHBUgdlocCaXSQStRmpKoXVkmpPXmTyJXtzakBWfcPVEWQzZglbjuDtRQlhrKRRhppLNroWfbRNrPbgrcixqBMnpqufWreOrytmxXKWJsacrsfcwPSKJnDcjAyCDFZtISHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ravnmCUsNTyHyNzBsrOKkvmebSCGknnsFRGByPilfpWTyZVryiZzTpBTPGLUEGPpvlAkViyJfBqKMdrPUtySLRkphqyGKErVgFItqdDTMvjNjXPiidepGAsKduFjDbWOeBwkiKRDajPjRcZuusVkSiXqQfQuszpXwTVMoFsANCBihMzRZPGcFRajMwpRvBqWoqWQeEACtJWPYpTIZHeWsAebQdNzDfHiAcaTQIkCBxxYvLVhjndVtTWpKIIqOMVSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jnXNswFUtGWmerBkpkCcbkBFidBmVICOfYpVMqOKVEYZWQTkMzPzIPliuqikadmjbPcmYCFbyGtSRFwiKuQqOvkyRTNJMHcFzXORKIVgvzbDFNheCkIvuntnUbeKIyAQdpzkNOeMTZPHBSOBCEhXuxWAkYnMiOZMgWqRCOpXeGpvKDPirHXGpoGEjPdCeQCLBkpgroPZrQiFtYDhLBVwsQxSvxdXdPPeUjuKDKKUDMGumowkucfNxroQjKFrIRWSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BPFoKZltqFqXifKLsxhoNIuBmKHCzyPrUsWbWMDAbgJQSYhbOmBQArALRofGgMqIlcVnZSveOkloJbRlpokHHLImSnkKGucAzivCKTbgyWiICYDhuiDlvJLoCTZBOdcFvGGJFXhcLxhmcNAzfzyAYtYuvHWVwUuALwzoCOsZpWKzaKfasXOLVZwHzrgiXBpKTjYLfFpGWvMHsSjguUceuJIhJGhZGajBusrKNuwxGWFOhoMgUMUgJcrJbuKeQmnSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('oUsXKHCGVoEnEbhKLeqszfQWwXePNhzpqCEJbLUyhMRJCoYdSIkuDXhnuOCrABvXJraWlrbACOpQAqcSkoQzVDmEStEYuPUrejXTjhMvALxLkjbUtZSRazfegOhpQdEEldmxqURckWrMuWCYSabztzOkVwXLYrdgbIgbJuclKKpYUavPldRdmFzsWMtCjavYKLeVbVOjIgsiNAPKfTtwJsnlDSuXkTugezGEpTweZGaToDWSfNASaUerGmXAIAiSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('repXFcLBaJSuFHMZEvVByZNWsmziojZcDnwXtWOqfyzWDLcuORyZMvvZDbaKBuzpMBrhvGecfHaEqtXQnRjPLPzkLCvSVNULXyTQrYwJukEJBTaenJZLgFHYNYPswzFHzjLSdHXuyvBZgJHICBzKqEaLHVytarnoPolarDFVgrGnXmWgnlVemoDkoFrnfjwwxSYbGqRwbFAflHAYzFbGfnNJLcxqkHXPgeFItJITbnHWHxjwPbOesXTwkAnWfPJSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('EHVUvGkOusBjGSbFELPDEdYruBRMICRbGvOZxaQacFnJADSDBpFhaHeFbDGpCVoNHDEvZCHcrCIISJUqFWFwZCxlKxWinzZRhVTqIoVnidFpPPQSodXyodOPwcniiMPwZDHWSDHkfRfEoHFxtwwDTADthAFqqzmHlurTebxTloTSQdrYBmoyWpAnlLtOFnSYmxPuWFWJxrJijMyUgrQJfTyKVuRdilHRieGkzPVjLYkKgeNbQqxCVclujuRmLDnSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('wTjTietmZfIdHFztclyMSpVfXFBGeexuMyiAMGdhoYtJTUlcKVrJylgtiHxicoZIfHbqRqKoYNvypEcsYWzIrSikIqXwKAmLVloKCUAHONorDiNBCSilFzvUAgIYNKnmzxhJFzupXORpGvpHAhjdUkTDnxNAHTzhEmAnLUWfBfwlWxrMIRNFohBPBIXWpegvoQuyExnzywFgYRtsrFBydVjVKPuLINKuFXUljTrysfJpzhjQbidBvwizEwqezMsSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mLJHujhbSVCWrPuisSYeufbSHtfGfSoMhrvimBwTtthVFRQWgXOFtpQyPXdXucGtUjoHqvtrNfDBDXpUzFwVRUagiADIyQbryCBUWshoPOBzmxZWhhsBOulcNKiLMSOxdOIQJzOIzIuMaQBUZVlwKJOJoCNLKlfuhPrsuojxReFuGKEowZlwfBOzBGAfLYneFpFiPQiaLPCoLFbUeMCpIsCpWpjtrmJhuqxzinANsRKFdbvaigyhXSvIVmmVUkmSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('zZbrVgWHACWqAEcwFWmMkFDPHUaYBUytzaTbmFdOLkBeZDfNqnuReViPSLDLaRSGZJBeSkhEAkSNwPFJPgjCnzuPyeVJYdBtLAwVSxAHiByGhnpNRdyLfcuawNiApSpmivyXdxQrprIeAppHpeugeYwwWNqBGlUMGCURFyoocIRTQjPGDOFsSkIgteaKPLejaxKaXcggsBtJStmpKBAUBrNQyNZWaPXKndkLHqpNibGYssbfAZYqqaUYwwKpIcfSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mpWhloQfcucOQgPeKFmXobbtTfwOxggxeslXlUXxBLyFdsfUrZDVCAimJXTCAUDKyNPDmhWtFVPBkFUpqawjuzDohlPLyJOhXZTggfXMdHGThBicBjXlcCXgHqnxWigGziYjABqJOviyqsJnAYeKKCrCoebnKXARrulEILJioWFXxvIZIjyZLHFdgwEiKdXCAKPChYutzvmJdubmizzNhBFJMriDlSFEjCAWpRaoKxOagXPCESFapBdkTzvnyGuSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('AuDadFYiEOeLqtcRjTIVrTjhLmlOPwuKaYkEdIcwsgFZaKCmKtmmmjqNwYtmxqGPwwKoedDHkCSpOpfrvMCxoQgaFIkqcokpWMLPuGcVsLPRvXrFvtzxSeehDObtXWlzrGuhyTeklRnEFYuxSxpULEpVuDKZKmXDzuSGPmfhwBQzDFBdxIpXrzecwViMTxVbHrFngLkDWdeCfGiAarMygNaygbyOHrMbTTcdYOMkaPUXuIgnbtGsMQwAphvFNShSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('PsmwgxRIsQOjgkXfHPqxEHLAHJgcroeykLKQnqbLnUVCIuQddaRMYvqruUquvSmOiUGjvtQcpwpQyRlLFSCAvZpDjDXNMvNSKETqgbqlUDOsHcLktyaqpdpkmwnNLfQwoDGCWvCuBHcmNGThppclTsehmsVsICPhtfzlXEqWXwNqnOROJyfSDYjkUTsVUgyUaYroLwQGasUvQLcOIINgDaEgBWYfMHfxyMTviReWKXWyEwGGkQpIyBFMlcBmtgFSHlwZXJZYXcubHVh'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('cfzZjXKlxfKUCDjigecfLcATvVihsEDkJuyBKYbJMNeoCzQcANPgvDNcEscORnMLxxaalSVLkBrYEHAnurdFWhXUcwSSajZESJUzqsNvcsMnDsWfjEnwbkCYzHabKhLILbhEaFfclYFydCymMySNpYJsaCBYarCqTmwoXLVVqadZGPASCVdVEIQpQNqWgQsPRqNZjzNyggmTrNJEKsxTSlKhqCjhJoqwGUrnJkgiLkAgYUIgDcxrCDXFPMkEhbRSHlwZXJZYXcubHU='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('kgSEZRWLjFyfcnNUePJXYyXouxjsAMidyabLEHYjjlodkuQzrOoOFMBFipgNVfSvpVduEQFZZSxrCCSIHqIgbfeHAziyapRDSWHFkPesSvOKgfbLHaRkZAiGCdlinxtPFEUPJWsnprsbOJiyaGRboxNtvjOzALfjZuKhbVKSiWolDVcrprBTyCScTztFpjENszJMRWzgXdOxRxsAEOHjCDBxpnrWeBXhBgQzwQFLTOODDrKUbeIZwLFnfQKVuUiSHlwZXJZYXcubA=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('QlQlkeJpfrYzYFjzBJHeajKBNYcZzfVjWsRZuRoybWAafPCCrkpTeNHnQexoHbFKjFFJnVyJZSogqUVVDKGeLIvJIVwXEtuWwkqMafKNElnyJXBWqTILJEzIOscjLndvUdPFRqhrPYCaTVQJKhbPArBVxCecMeUjKRayhzXePZTuYoZEqrvZyGGMJhhsvummbFUXzpsYQPMlYempkTHVWhqDCkgFDzqobgZpaHjlVYiEvQfsbMxIAoHaBmIjxxfSHlwZXJZYXcu'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('FAKRGaVbeGSLQbKIgkqxeESDMxnhUUSeUSquipWItaKaBGqweYPdVqWddWYQHzjlTqjAzDXwQdubfiQzmaeToYuRTkJhOEbRiTFvGNKzNtVxhjRBtKZawEDJrUzBCauqYApjpolyoadBxSSQirgkvvBzVmwXVFEYvsUIDifHmVAyGJntlsuJnRmSVrluFTkQgUacRxeoDvzcglkWaJmNFKlwXKUvjHgQjWnvBHbRAyrWSMyAVRYChjWDStDdHqmSHlwZXJZYXc='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('FOZplNMzMtkPdyvomZznBIPoLivVTuxzSbGJxGZyyIgPGQhSmyafThBimusSqtGFqyuagtDtpJZWliKaxbixhpOPUiIYTVxmdECKQEeANiAGHlkObpcwHtrYWlRRPaToxwsWqNIueVfldYnGvMYeZjygLFHtTVkUDsIMjuRRHyxocVNYlzfNiDCphaQgwnoOMpOqRbHrrGcEhMcqvPFyjjmJJUuNLiGPBtPrKHMyNfJqepPjFuseTAOqdezqMDySHlwZXJZYXc='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('KVITudesxNahWmYFWgTLlxgSjRFbieFWQsQmwXsfbhrRHTgHoZyNnrCFVXzmzCDBXrEfKZqjZdAkxeiDICuTurUPCLISqeaBnRxywkkaGWMDTIgXtMtLEEjIKAEACechOUPOeGuqCFzsJbgPFmYHeKQrOyYwHDzNlsZkXOmdagBwxZMzyccpHrhtePRpeRIUmLXSOPxQgKTsEOEHfmVIZaTjKAGMuwAANwKNwwiMQKDGkHwWnHUpGXxpDIjpvXJSHlwZXJZYQ=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('CPawRTkwbztrtZfkXuDlLytzRfDKrOxnuTmMcQpIcMqBewkVYRMaAjpjzVBMmifTxIIATiYSOrUSfUHlFJlYTMZGwtixVapUprXzwoWuWHtZcEDqwAIBHmyuiOCoTwmKqrIiOqcwulEKgwlVOTjdJWILSqYkonfuGAdcLySIsCOEnCzNITtzwvhYihmbMhvZfZOSNNkmxMTagvBNyXUpAQdgIHSQaATPrWOOvOLMhXExRjZyjSNvfKBfxxHyilHSHlwZXJZ'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BzHiAPAtuBlNkqJlWmFBDbgLoiAeTbAgXIbGRDklPrcipUSsilNOZzbhASQYMVDJrfyGvqsTYwfucdbZIMfvjxhhcwfycXeBafthMBxaEieoQaEdJAWXiOJEsRbNZlzDRUAvlhiVAoZzJuzORPvETMYllFWXfommfMQDKeMwcpdpypxPzcdlGZDZGBdsJDFVvtJnAYVaLeDClXdeAwdtyHtaUSnfmMTNqUsOVNAldLQyjIycpeSFoCLcRUKPMyLSHlwZXI='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jNOVXolqvnQYQhMyXTxLxAvzBFoGXXoXizBxyrCRULgRWZlaykcTIbfbfNEgJxHpbQTzoHbRYRwIWcpWjNmBqwMvUOiRNHjbNnLPgRpfQcLDAuqiXrGQdegFPqsJgmkfTTicMFKFoHxlaNyQkInLCnKfAujdUTMXlNYEoeoVouCRBaoDrTCNfurLfpDDPVUHbpDIScZJgSXbTLeGoZmdamAmFhEnLoCMAzPgCmNwDFWlxmEZYMZJNTaRNWfybeSSHlwZQ=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('oWRkUCAnWRtVkkTPjVqpiBwvkzsljJovwoTbjhDqXQouoCNNLwwkJKZpwbbOqVDAbCVzrVEDaELFLZAnrWUykWkvbAPySAxDWPVkoOmWMJyDJkHQnsFMbYZHPzkkPgsgDcmNkScCnFlGSCvBXGIudyJxolUxgBXpfEIMezDMxkdJWJLysNLjSbOwbnfUmQVYprysxlVmwfMlkVHqYHJYtCINJMwFwMCUydMaYvtGswvmhKCKOIsjYewqtzTaDerSHlw'),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('nCEniUfXeNyLaNUQsEtnObFkHfOyyllyWsUQaDogNiqyRMZJVzxtqRTrfdUOBPBjidbNbbOXrfrmoMAGNmeRkdLCTyIzEivwyZAdvNTPsABjqqcWWgGZnksHlPcZFjoQvktuBItnClwVODxlrdrHfhDsMqkNwQewufBfOCfsYGxExCiuVGCsVQipEjUVMbEpDTDSnaXmRGLmSRskCqdZAUKBgPfytGoAVlrrctBgnpgsheycxbPksPRXZaWOwLqSHk='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('tjkwzKReZoPFeaKbyEQuDvNIeAWrVNyztDTXKFwdKTIzMWWyzYKWArNeHPrHDEkNcVMXmiqjJekfAJqffEgmQqbaGgaKULPvamxvIhDVAfFCEUANaedRmNXPPCdBeAdrVXSbtIfKLzacSUuFofxzYYwinVXJutXiiqdNtRfPvcBBLivdjvfzlxVGkvPlNathgcxSlAYyUFEFkGOVAhDQbWeTpPitHMwwQnJmyJLjstEijGFnNPdNzHJeqdSmNnvSA=='),
                KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('EWeDtFaFfVARzxjFHgCERfKUGQySjqzrfSEuQOnsdttHDPTKaIyWPhyVrkVkcGulAJimXYjTbAkdfgwPCgBKTubfzzNCpbmKsESvEDETImlXEPqIfEIRXFAJuzDpsPBHLrVLrSCVglBQybhbCdTgEYrJYgMhPgrcwARBLJMcehmKmWilbaqoqLPeCzqUuDFjMfmoIGIzNtgXniNsVwLonawBeswdREUhkgTQCcFHNgxvrDtuOYYGFxqCZVUbULz'),
            }

            local curtime1 = math.floor((i_global_vars.GetCurTime()) * 3)
            local clantag_string = clantag_HyperYaw[curtime1 % #clantag_HyperYaw + 1]
            if clantag_string ~= old_clantag_string then
                cheat.set_clantag(clantag_string)
                old_clantag_string = clantag_string
            end
        end
    end
end


local player_flags = {
    FL_ONGROUND = bit.lshift(1, 0),
    FL_DUCKING = bit.lshift(1, 1),
    FL_WATERJUMP = bit.lshift(1, 3),
    FL_ONTRAIN = bit.lshift(1, 4),
    FL_INRAIN = bit.lshift(1, 5),
    FL_FROZEN = bit.lshift(1, 6),
    FL_ATCONTROLS = bit.lshift(1, 7),
    FL_CLIENT = bit.lshift(1, 8),
    FL_FAKECLIENT = bit.lshift(1, 9),
    FL_INWATER = bit.lshift(1, 10)
}

local player_states = {
    IN_ATTACK = bit.lshift(1, 0),
    IN_JUMP    = bit.lshift(1, 1),
    IN_DUCK    = bit.lshift(1, 2),
    IN_FORWARD = bit.lshift(1, 3),
    IN_BACK    = bit.lshift(1, 4),
    IN_USE = bit.lshift(1, 5),
    IN_CANCEL = bit.lshift(1, 6),
    IN_LEFT    = bit.lshift(1, 7),
    IN_RIGHT = bit.lshift(1, 8),
    IN_MOVELEFT = bit.lshift(1, 9),
    IN_MOVERIGHT = bit.lshift(1, 10),
    IN_ATTACK2 = bit.lshift(1, 11),
    IN_RUN = bit.lshift(1, 12),
    IN_RELOAD = bit.lshift(1, 13),
    IN_ALT1    = bit.lshift(1, 14),
    IN_ALT2    = bit.lshift(1, 15),
    IN_SCORE = bit.lshift(1, 16),
    IN_SPEED = bit.lshift(1, 17),
    IN_WALK    = bit.lshift(1, 18),
    IN_ZOOM    = bit.lshift(1, 19),
    IN_WEAPON1 = bit.lshift(1, 20),
    IN_WEAPON2 = bit.lshift(1, 21),
    IN_BULLRUSH = bit.lshift(1, 22)
}

local move_types = {
    MOVETYPE_NONE = 0,
	MOVETYPE_ISOMETRIC,		
	MOVETYPE_WALK,			
	MOVETYPE_STEP,			
	MOVETYPE_FLY,				
	MOVETYPE_FLYGRAVITY,		
	MOVETYPE_VPHYSICS,		
	MOVETYPE_PUSH,			
	MOVETYPE_NOCLIP,		
	MOVETYPE_LADDER = bit.lshift(1, 9),
	MOVETYPE_OBSERVER,			
	MOVETYPE_CUSTOM,			
}

local function SetViewAngles(cmd)

    local viewanglesinfo = i_engine_client.GetViewAngles()
    local viewangles = cmd.m_angViewAngles

    local yaw_value = 0
    local jitter_yaw_value = 0
    local desync_mode = 0
    local pitch_value = 0
    local Spin_Speed = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('UyQgkkCHDrHCHSsmCecsjvaMgyHbxFZedrPEfPhXBNzaHWppJQZRZoEIPgZcoOPNQUPBsqCffErZsqLZQFeTBwmsaOGzHpTXdYFqghcVNVBsrwPgyBGWBkPeDUOTMINJJwHovZGtjtOmRlCLqRCxoIXVlImxCVdmYItCKzScQAEJoUGYZLniZPloSaLklazagnnljZWSqPksnanAtKbGGSBQGFycjwnTjpHohNuZymWlciJhIAFElVZEnjXGSbyc3Bpbl9zcGVlZA=='))
    local Switch_Speed = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fBjReOYznUrXguJDFYvpWMGdBngWruJQHjxchyxIGvKoqNGMAoAOXQJOqXwjMMOFhDLARRgPXEKArlxPHJAuKtDALIDyGqiqDjXQwzbBVgpLZMdwyzwsVAwhVXVGoBaUHLnCJYRucXcTxxPKydWqtJOrQzUZMZnFClcSHTQhSLkYwDowQEhbdnTtWUeTYqVuEhaXFeyuRwpMdcfnclcUDIEDJkOjHuBQNAGkJisKdxrygaVlxIcNamagxCpxLKhc3dpdGNoX3NwZWVk'))
    local SwitchCustomAngle = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('IcwFKYkeTYTLVIqcebFTHNKnpiidtndYYxWcSdRFjqRQdOjSsyfMGxkRdmcuntkhhmMKgzagKvuWvzYUvZFUwHynseSxBOsWerBFTYBfxhzPrjjfakcUcNFxPEzzLrbnKxhtlXvQZMCXKAhCFWDmvhHnvShWmHgkmDUhfBXRwDkDsmOszqpIxbxbLLUtzCSQyRxRSVwlgcQUAjJaTuQXZSWtGIbFnSvCxLAFtXgRBVnhZRdAldBjpPhZufBxJOlc3dpdGNoX2FuZ2xl'))
    local JitterCustomAngle = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('fnuIRRhcCpxsxlQfEpDObfuGGQmiQlwIywyHOAvYkrfxhzVHtiJtayKrPjGUpPRahwdGGTROLTJQrEGbJqIhcXcFElftgVNLlbgeubKqZqsFXzeGLSRDEjeibNvxPWFIfKemSrQYUnfTLrDbkCRCvzznqrXgLnPpldCsmkaTAyDpnLrJQXQNVlOuLgdzCUdBThaMIIJmeXgxwZrANORjCEHUoFeYnBgzDKtsppapIZAmRStQDXnJCtGZdbugzTiaml0dGVyX2FuZ2xl'))
    local Switch_Jitter_Duration = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('YkLoohVNRiFcfIMreiNTOSytchUFUFtKsDnxVHdgRUyOGMjRnTWLcddRNCBzWqtUyHtNHPfoCSIszSiGLkqYyZFZwGckivfPIaYccQxzNxtiosejIBSMfCPwaJJEulFGKYJIbuBzQQPWmUOORrNqrfrboRRnQwleFOvoOKdUPXbzORqxigIcGVizluXyoOIphnxrRQOHAEStSZclOXuYbzPebRUdnnkIeXYDFNPgboVObREviZXPghiUwCVVYiOc3dpdGNoX2ppdHRlcl9kdXJhdGlvbg=='))
    local PitchMode = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('DxvtjFvQjVIHlkduBfWiMDlEdMmDvMAKkLTiausBlYsYFtNHRDCbpCsqqqAllLXjSijsdTJmrbigIcXxaalYYVnOFnQMZZTKwRyMnmKHhksjccjHDoBYLNsvDMfBPJMGOVkeSQWNqsDmYqMXTdRilghEzBWrfeLWmYmPnlvnBMbPNHrueTuVEylaFaYYAhNkUdlmvbMYAQUCVMyDoRtXxleKxkiRUnuKMDiAXBrgMiHDKqyrdtXSowvTLazbtvEcGl0Y2hfbW9kZQ=='))
    local PitchBreakerValue = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('EzkxtGCADszStguqtPZWOmOnbSeRPFMfpMNILOLNYlUnVRcQVwUGzdZBweIRFChxxJpmejKXQrIDhQIVHKcAeXxZtNODrYFjWxhfBFiPwWUIMSBovsOLGAdVIVfhieutOufbxMXJyLguaRChMuadeozEypdJMdqQIeMcFqeeFNWyaJwrjIxVdSjgOuBPjkKsBACoXvIGhADkjWmRLbvuOEHFTLqNEGRBaLuwkyvGWLGBxfQmrczOukXLvMQIrbGcGl0Y2hfYnJlYWtlcl92YWx1ZQ=='))
    local CustomRollAngle = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('peWVkmbpaSQSBlNXPpvKsACeQvVbndKBYkxjGPWfMeDphlCdxhtHrtXVjYoUfDAIfkoKIGNMzLfeJhWjBcPRFGSOIsqoVwJYibRFvzsLyBAdGFWPGTGeDaASwanccxJZLMGLlDuQjttEAcnUfHDGxGSjvlusimYxvQtBYyLCtLPqYmedMWDwVUJOJImOUinnyxOBBVOrkygihmGzNUzvCVlDeUyPxgWrGIWOCGmdBtSEBLXBXJldfzduHGZpXLjcm9sbF9hbmdsZQ=='))
    local RollMode = menu.get_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('faxvzcXurfbAKKqimdtFOjIutisUMQmvXAhjEeUoIRInRjGkvlspywdAtXVAxjFKkZAfcpIyAWhmUWKJCplkCzUoYthYtAEHXuhnNVzbMppeDVvRuljMucxqpytUiiSKzcaARSYGtsFItMLICUDIpCXGDgHmdjJfnRUqEvdmUOlfSsrOFXHZKBXUVirgkkqHVCzyMeOZptvAZxSoDLHOqvZGlEctqKmBdIbCKGoXRKkwISnNIvqtCGqwUldGKkycm9sbF9tb2Rl'))
    local DefensiveAIR = menu.get_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('BKgSuANAHXPuuIDBzdvLAiBQSRmExALGOMRTTupQbhIiioCSCNHkzdHkMiNbxplXhqBnXTCAEFMwPsZkZEGdpTIGgplDUjeoAWuUDRvWaNnvwcoJwgVnZLPTfRslMNJNfEJirOShsUaqjhBDAFjFucqldCRzjxnxBEkPebRpHjZUvcWrYUkUhmVrqJHjxnlUBZVKColGiHplMaCuHEDyGPcSPRUHbRTiWvzBEIIpbGtiVpLNJoOkZQFDlhUYwUwZGVmZW5zaXZlX2luX2Fpcg=='))

    local GetLocalPlayer = i_engine_client.GetLocalPlayer()

    local local_idx = i_entity_list.GetPlayer(GetLocalPlayer)
    
    local flags = local_idx:get_netvar(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('QUCJfFEUMWXVcoAiGeBUIhBDpFbXTqfAkhXotTFbkWEUCRnlJNfiseVenlATRghXlRDtREtQnFehSvznYXLiyjWSQRzqvMjzFLWJdQJRCJCUJvMIaevOGsRhZVbTyQPwuaXnvmDKnWMKqJotKWOraDNksOzqJPORQbQSvwzWApbHlVLxYNspWrCycyGAasPucNpNfNsOAVQcVqRvYOszythtFmyAWoEYqBaXzPsKaQbnzFuzpdQXaNTurkcOITlRFRfQmFzZVBsYXllcg=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('jqnvBnrRMINVJhiYaPWxvayLBpEMFiPhgLVqUwFIElffdXWemCpioGaWOzBhNjWJueRUjriHKdzQGKiHxJREVGOqZqSDgvMhceqztDqZJJdkebCpjiRsQCkrApiyIGuRtYrLheSwVBdelHMZSuzkoXYcgOYlWrHswFcpvngHVRMoLIjBmPiJiJkdAixKCgyhsFeFjDAMYxAdrbqlYjbFzmniFpyQatIXfdIWROYhbvdfRcZtYnNeUpVMqHunjSObV9mRmxhZ3M='))
    
    local m_fFlags = netvar.get_int(flags)

    local m_MoveType = local_idx:get_netvar(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('yxzOhRHjWBXDPulZqgyYcqIqRlnuhRvVxZWTHqsRCaKlxZgnJqOazUatPozWGFdIjlqcqdFVoLxreJLuXZjNKDplidflBzFcuxolShNIWzqNGMRigBkYpiJSANjFGebAMsLWtFSyouhUNrLOFnLECAKXJDzntqyJLLrCiqnBgulVxzXlGkcNSDHKRXiNeQAfJZBKPuUWmWNZundAQzDDgjwbcloHXJhFkMdFygNhbFWabUBGZbfDRYSTxscndqPRFRfQmFzZUVudGl0eQ=='), KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ptAPifYHAdDbXyQhMmRPejrTUDSPpEwkchIjYYWoixIwolOIKbvWDjArbWuwiJlfLojQyNqCoFYMVtsuQadoSSIASEknwfIydYfJnmfnxNMBfBQMFIKZSozYbnUUVIcOeImpjGEgFscnMGWdlzyZGCRCucpHrDwshQnJSAsSQSJAmWyARUjPlOIrERzPesoIGMUwhkRysJjoAoKKwAPvwItUSaOSoTmDDIjoJiZtDqBmziDxfdqfaZEatPLYkjhbV9uUmVuZGVyTW9kZQ=='))

    local MoveType = netvar.get_int(m_MoveType)

    menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('KqHRcvAXQovCrjXTRCfLnMVrikAzRIQQDtazUvTRLtlZRxERlcOxngTkEJINmQozIaCpClpkDHCqnAkClKapRZRYYDEFhPUogqFtLkASspwYRQPmyDqiPfOTeMLCaojLtABpkuzKPLECXKwfmMIHDpDtUsyxsQsLFkfCHSVPdqNQbzltIfFdiznJXzooZYwyrxhFQvcppHYudnasyuOhtigQqhjkgCiJOmKXNHIABExrgJKVNMIoYzfSrRUpoKEYW50aWFpbTp5YXdfbW9kaWZpZXI='), yaw_value)
    menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('mwgNiKINYAOwzIGRVvRzlTTaDvcOMpRQvVblFaSnFuHdPOBrihhJBkfmAtwFQEjWxuXDuDaGxXiSUDusXsfgMeeBOHEdsDNNawQQdAAYsDXzVlfDYSOhOuGGQGvZLMQPTgajhXuDOzdFPCkiDoPGwipgOfDnzxBeTQqjhupehgbSgoyOSJaGMstjCKXjXqCxHmviRDEYlwMhZXooCRByrvEBEIguBcRnNguUiVFdtYIooQESonKxeFxdRZNweitYW50aWFpbTp5YXdfYmFzZQ=='), jitter_yaw_value)
    menu.set_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('iyzUxyiHbdrXQMMjoTeXXXhoBlJjvCVILizqIJWgNmrDsjLiUgBDXqZXBPHYMVoLWCvsNRIwPhMusaRiyxZLNibRtynyQwDvsBqCqNtTvBcxtWVIgBfqNMrgenPeMgYnfKnwMKuJNpYkQtSEtkuVnDqXhVgeJZnzAQFFvDAgWbcpGkALEMIXzLOoPUGTJNpnGwcVeRQhkGdQDxxrbYHgyvqQZpxxobtrnpmyHkXcGTDqGYTjGqQJpqzsKSYNRXkYW50aWFpbTpkZXN5bmNfbW9kZQ=='), desync_mode)

    if bit.band(cmd.m_nButtons, player_states.IN_ATTACK) > 0 then

        -- do nothing

    elseif utils.key_down(0x45) then -- E Button

        -- do nothing

    elseif bit.band(MoveType, move_types.MOVETYPE_LADDER) == 0 then


       
    elseif DefensiveAIR and bit.band(m_fFlags, player_flags.FL_ONGROUND) ~= 1 then -- In air

        local DefensiveYawArray = {1, 2}


        local spinMax = 360


        local spinArray = {}

 
        for i = 1, spinMax do
            spinArray[i] = i
        end

        local curtime3 = math.floor((i_global_vars.GetCurTime()) * 3000)
        local spin_integer = spinArray[curtime3 % #spinArray + 1]
        if spin_integer ~= old_spin_integer then
            viewangles.y = spin_integer
            old_spin_integer = spin_integer
        end
        
        local pitch_up_down = math.random(1, 2)

        if pitch_up_down == 1 then
            pitch_defensive = -50
            pitch_defensive2 = 89
        else
            pitch_defensive = 89
            pitch_defensive2 = 89
        end

        viewangles.x = math.random(-89, 89)

        local DefensivePitchArray = {pitch_defensive, pitch_defensive2}

        local curtime3 = math.floor((i_global_vars.GetCurTime()) * 100)
        local spin_integer = DefensivePitchArray[curtime3 % #DefensivePitchArray + 1]
        if spin_integer ~= old_spin_integer then
            viewangles.x = spin_integer
            old_spin_integer = spin_integer
        end

    else

        if PitchMode == 0 then
        
            viewangles.x = 89

        elseif PitchMode == 1 then
    
            viewangles.x = -89

        elseif PitchMode == 2 then

            local minValue = 0
            local maxValue = 89
            local reversedValue = maxValue - (PitchBreakerValue - minValue)
            viewangles.x = math.random(reversedValue, 89)

        end

        if RollMode then

            viewangles.z = CustomRollAngle

        else

            viewangles.z = 0

        end

        if menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('MfVBZdmyZWqXHibWcXwJEVMhZtbfZlpbXVtMIBaRLkWzasXFgHEgAlUdwjLFeMJyWuMnLBTGcGdIanlgCytRMQOmhNFgLbkDOmXcIAMClpjwUwcfqjuyBpYmzaYbnYhbHJlThhJSDTGbupTTPBOHEqMCSLbhclmDvjRDrIAPzIfCwYCscDGFaMJNUSfTlWkkgTexaxRMNjdqmFGtMUDFiyZlaiygJDlNZLxioTnfdWAFeSNPHhZOvbeZzojJqddeWF3X21vZGU=')) == 2 then -- Switch Yaw
        

        local centerOffset = 180


        local minAdjustment = -SwitchCustomAngle
        local maxAdjustment = SwitchCustomAngle


        local numAngles = (maxAdjustment - minAdjustment) + 1


        local switchArray = {}

        for i = 1, numAngles do
            switchArray[i] = centerOffset + minAdjustment + i - 1
        end

        local curtime2 = math.floor((i_global_vars.GetCurTime()) * Switch_Speed * 100)
        local switch_integer = switchArray[curtime2 % #switchArray + 1]
        if switch_integer ~= old_switch_integer then
            viewangles.y = viewanglesinfo.y + switch_integer
            old_switch_integer = switch_integer
        end

    elseif menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('RiyPyRPuVOXYQSdUMsELtlyTmBfQmICuSRCiVrbjzVCTClqhFFaabXGRxdNzIURKiffMDjaiLFWmjMABapbmTDfpKOjoABlihHFZJMsdWeOUbTasSEkGHUoBqPiYSWlaKkXBJopUwYSvDSmsynIfBHDIJVGaxiavOGUYKdylnnBCaeiMeEzVdnDroytIqaodHXwIJmSRwnJQBMnCWIiZaYzVYSHHSGfmJOBbHlmZyeYllTEsjLBbKIxyIkcqiOSeWF3X21vZGU=')) == 1 then -- Spin Yaw


    local spinMax = 360

 
    local spinArray = {}

 
    for i = 1, spinMax do
        spinArray[i] = i
    end

    local curtime3 = math.floor((i_global_vars.GetCurTime()) * Spin_Speed * 100)
    local spin_integer = spinArray[curtime3 % #spinArray + 1]
    if spin_integer ~= old_spin_integer then
        viewangles.y = spin_integer
        old_spin_integer = spin_integer
    end

    elseif menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('nZqjlWpqSPwwIjTglMOpFwAaKzEJPocecVAGnnJrGzWaRDCoyLhGEwhAHzPwUmPtPnGQnTPkUqeJwmqGoyYvITiFIPzZUURzFmMOObjZBajMlxcxKUTQJcmtHBpQSWSkhKLZFuiwHKsGmvGOSAzLVItFEyEvieBIXfsZXKbscHcqAAypFMQjrFBNYrlSZYYLgxRLordRXDJGNendIITvaBiugjDLcjiZswoopdshBnSvfFxFfoFiXOcATynPBijeWF3X21vZGU=')) == 0 then -- Backwards Yaw

    viewangles.y = viewanglesinfo.y + 180

    elseif menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('VvhXisZBzqgjlQSuiARRDZBlQcMfRcLqNBUEHPoNnsIhYATHUtiNhbbQmFvEMAwowESxwbQYzSZqsKktaSwjeXIfNvEuLJIPcpdVNGAXlchLDCpnKUarfbxHcQPEHRKaLuVGvJrcdvcVpAkjizyHRfaLjAgmWxQrrDKQVIFvQwWBkPSUKFGyoZpUStJpzzUqVVYKszsTBTFUsyAXSuzRMCLHCTKmVOEZuqwtliJPWBiHDovdIJSkLqAeyQVHewTeWF3X21vZGU=')) == 3 then -- Jitter Yaw    

    local centerOffset = 180


    local jitterRange = JitterCustomAngle 


    local JitterLeft = centerOffset - (jitterRange / 2)
    local JitterRight = centerOffset + (jitterRange / 2)


    local Angles = {JitterLeft ,180.0, JitterRight}


    local Rate = 1.0

    -- Function to update viewangles
    function updateViewangles(pCmd)
        local curtime = i_global_vars.GetCurTime()
        local tickInterval = 1 / 64

        local index = math.floor((curtime * Rate) / tickInterval) % #Angles + 1
        viewangles.y = viewanglesinfo.y + Angles[index]
    end

    updateViewangles(pCmd)

    elseif menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('ZTHbGmwZDptqpoXZmOinyDLdthpZJCMTkRBeoUnvoxCcbwyZPyqlFaddbzvOoZVHzgltOMDoOdJBAMGYJAkpKUtoghBEoVOEzXqlXPXKAxWqYUewCFCQfbASrzsFODQXPWNRLgijrUIBWPuUJMDUZbUaCRHTDvngqHNqXvSCmKDHvFyDebOktMCZJRjjiBhVZEEbygWdVIUgamHDZMAHqMJqVAypFDFsygRPgDgrqNgwjoZdHloLPKNksjPASsdeWF3X21vZGU=')) == 4 then 

   
    function JitterAntiAim()
    
        local centerOffset = 180


        local jitterRange = JitterCustomAngle 
    

        local JitterLeft = centerOffset - (jitterRange / 2)
        local JitterRight = centerOffset + (jitterRange / 2)
    

        local Angles = {JitterLeft, centerOffset, JitterRight}
    

        local Rate = 1.0
    
    
        function updateViewangles(pCmd)
            local curtime = i_global_vars.GetCurTime()
            local tickInterval = 1 / 64
    
            local index = math.floor((curtime * Rate) / tickInterval) % #Angles + 1
            viewangles.y = viewanglesinfo.y + Angles[index]
        end
    
        updateViewangles(pCmd)
    end

 
    function SwitchAntiAim()

        local centerOffset = 180


        local minAdjustment = -SwitchCustomAngle
        local maxAdjustment = SwitchCustomAngle


        local numAngles = (maxAdjustment - minAdjustment) + 1


        local switchArray = {}


        for i = 1, numAngles do
            switchArray[i] = centerOffset + minAdjustment + i - 1
        end

        local curtime2 = math.floor((i_global_vars.GetCurTime()) * Switch_Speed * 100)
        local switch_integer = switchArray[curtime2 % #switchArray + 1]
        if switch_integer ~= old_switch_integer then
            viewangles.y = viewanglesinfo.y + switch_integer
            old_switch_integer = switch_integer
        end
    end


    while true do

        local mode = math.random(1, 2)

        if mode == 1 then
            JitterAntiAim()
        else
            SwitchAntiAim()
        end


        Sleep(Switch_Jitter_Duration * 50) 
    end

    end

end
end

local function AspectRatio(stage)
    
    local cvar_aspectratio = i_cvar_manager.FindVar(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('JqdGPnBTgxpDhpsTamYXPkFtQtAPQvxFTvRnvppaYvaSpmmoFISzdSTGgkQWlXHPTeTDpVHQSUribXjdAsslYwzKHaKhgWXjjcmKWzYBEUmeQYKBmfsZKRYYyMuKZUEBuYtIgwoBGWPFobmmFbwtHuFHvlfrIHuGRivbRBnaFvECRLFCPhVpGbdAubeYSFrOHyWCIbzYQKmSrILvyOXxJcNwCJJXNPKkDSsazZugEoJDUiWjafrAaUzkHXKudSUcl9hc3BlY3RyYXRpbw=='))
    local window_size = i_engine_client.GetScreenSize()
    
    local Aspect_value = menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('nOzyLwOcNANvrqCQDsfuUXaGpdjIFSiKBVjzvyzXetnHCWpOggYdsetvnVURALKvhiAYPrSeUsOEyXlADYHXOWdHxxYiKOoljwvPytGGzVrAsHuwixmiqttpYiAXIDohgisoHUhZXlxarczGWdXVempTWYViVDGZOMldCEDxLbuvwotWrFdsYCydNNjpCZYcrreYKjyVTnpKtPZfYbembuLVERhVhhZUrTMkfIWHHBbvfSXgpUZnyuoHFVzNSIYYXNwZWN0X3JhdGlv'))
    local Aspect_Enable = menu.get_bool(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('AprnzOUsXLgFmuItgmMHRtkNxxBfZbrqcOgBmeRfAtadFRfHPBkSYQxEFzJigHmuuSRUdIhRFjVHzHJOajolMatJWNUcNGfsvnLOrNCpnOhodhBIrSRiyITtKorsVrBhIekaeSyhfBRjElvsXoyVuUqraecQjxjKDcqXAcoBMCPGnCwenbKsogeByNxbKwOtxSwogPClqLZtfMaKWZClfLkAUhylIaTRthSNDiMIrmNyQtjRKSGOmmAXzUCRqpfQXNwZWN0X0VuYWJsZQ=='))
    
    local SizeX = window_size.x
    local SizeY = window_size.y
    
    local NormalAspect = SizeX / SizeY 
    
    local ratio = (menu.get_int(KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('xgAxxdZRzBzDvxaOxmtDbLoScDSfKRpwsMbBVJnuJiuiGoyDOkDHJCDDwfxCEbOpmSZeEcewIfLJLiVQCWVhYCNgIqCEQthvxEkGUqBsixUrQHDiGYIXrDduXiZOBWWQnIVJTRTkKXArTsAMNlsVJUQXQuAvKQMsMxdvDNFuVupldPMImdlpXcMaTwCglJvEFvMQszxguEbqaguoYFMiClBxXHIZXbXBJmHyywjlHEvGgIgBiOdMfUXbSmOkHkDYXNwZWN0X3JhdGlv')) * 0.01) / NormalAspect

    if Aspect_Enable then
    
        if ratio > 0.001 then
            ConVar.SetFloat(cvar_aspectratio, Aspect_value * 0.01)
        end
    
    end
    
end

cheat.add_hook_callback(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('gowSVNuRfizQXzGFNxLRKjWjEZYWBMZZutklZRAozxzWfpRRYuapGiAPvWSTLaznpAQuTqznNkuSNYfmNSslCiHKNBNHWbwvFlbrHTuqIYNcOAlaSqRbHNxgDXWKBLtuUcevQvmQfPNmBPhMgcXAgbGNVyxlhVCWmbVRiWBrlMyxJqGRjWLcqVjrFNuUomFlByUJjrqmOGTlHBXmzqptitdiHwjoIzXnFNRocNXPpUPvGDooRxHMczfRySEQIumZnJhbWVzdGFnZW5vdGlmeQ=='), AspectRatio)
cheat.add_hook_callback(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('MrRpeiBDwTLzrIXqbRFTrGlCGCNUXmEjYpCMkHlnYlHqFlmtbGggxEDCICMrCIJacsHXXwCjbVpHvgAdyvWLXrSZbazBuZiiWzBjxafaXrlCzPkddUXASsGcTqknbYExAhSglbkQTvljimAodGrOFYeWeaaiLqbseHhuvTaYyqYzCBKfoNcXrntaAyDFTOUGrWHmdnmksphCYjzTxRsQSgPnnUTDHvTYfbGhvintreJwjPyRkQOrmveFQzBumHMZHJhdw=='), AntiAntiAim)
cheat.add_hook_callback(GLOBAL_SCRIPTID, KbOGKSRxBEnFpdzFFuIeUcDnlZkDawJinfBhWrGwtstNNnJprbelLczSsfKikQvJCuyrHnHpr('EDmGIJEtnBWXQutnVOhNLCzrOvAolPnzfweYXKlELCofBTZxIuuvpdaPNWMDIWWnPPRDgJSbzdhzgtFGpUZOANorbmQvcVTervVQpPbCNZXlJVSmdtoQTFHlmqglnvyPVYMzQBRaqXyXdZtzqYtyJoaHnAmCZUOyKafIXdXLAcBZoPxpBFpeSzuSmCsphMShbqnGRslZoeSFFZyqUKJkgzKzfpCcDDpIwpjaNRTqLHGxozQMKRKrMlcCrwhIsEbY3JlYXRlbW92ZV9lbmQ='), SetViewAngles)     